Algorithm-SQL-Study/Algorithm-SQL-Study

programmers/17681/Yebin_17681.java

**[프로그래머스 17691번](https://school.programmers.co.kr/learn/courses/30/lessons/17681)**
<br>
<br>
- 지도의 각 행, 열을 비교하여 최종 지도를 만드는 문제
- 지도의 각 행이 정수로 표현되어 있고 이를 이진수로 변환했을 때 자리수를 n으로 맞춰야 한다는 점에 유의해야 한다
<br>
<br>
- 이진수를 만들어야 하는 문제
- 비트 연산자가 생각이 안나서 진짜로 이진수를 구해야 겠다고 생각함
<br>
1. 각 지도의 i 번째 줄을 이진수로 만들어 비교하기 쉽게 int[] 로 반환
2. 열마다 OR 비교를 해서 # 과 공백을 저장
<br>
- 시간복잡도는 (이진수로 만드는 횟수 2(n-1)) * (각 행이 n 개) = O(n^2) 인데 n이 16이라 충분하다고 생각했다.
- 공간복잡도는 어떻게 고려해야 하는지 아직 모르겠음.
<br>
<br>
- StringBuilder 를 쓰면 더 빠를텐데 오랜만이라 방법이 기억 안났다
- 비트 연산 하는 방법을 다시 정리해봐야겠다
<br>
<br>
<br/>

[공통 - Yebin] 17681

---

programmers/12951/Yebin_12951.java

**[프로그래머스 12951 JadenCase 문자열 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12951)**
<br>
<br>
- 문자열을 한 문자씩 조건에 맞게 변환
- 이전 문자가 공백이었는지와 현재 문자가 숫자인지를 알아보는게 관건.
<br>
<br>
- 문자열 처리 
<br>
1. 이전 문자가 공백인지 알아보기 위해 flag 변수를 활용
2. 현재 문자가 숫자인지 알아보기 위해 Integer.parseInt 해본다. 예외가 발생하면 문자, 아니면 숫자임.
3. 조건에 따라 StringBuilder에 잘 추가해주면 된다 
<br>
- 시간복잡도: n이 최대 200이고 문자열을 한 번만 순탐 하면 되므로 O(n) 으로 충분하다
<br>
<br>
<br>
<br>
20분
<br/>

[개별 - Yebin] 12951

---

programmers/12939/Yebin_12939.java

**[프로그래머스 12939 최댓값과 최솟값](https://school.programmers.co.kr/learn/courses/30/lessons/12939)**
<br>
<br>
- 문자열을 숫자로 잘 처리해서 최대최소를 구하면 되는 간단한 문제 
- ~프로그래머스의 레벨 시스템을 이해할 수 없다. 같은 레벨2여도 난이도가 너무 달라...~
<br>
<br>
- 굳이 따지자면 `문자열 처리`
<br>
1. 문자열 분리 str.split(" ")
2. 각각을 int 로 바꿔줌
3. int[] 를 정렬해서 맨 앞과 맨 끝 원소를 반환
<br>
- 시간복잡도: 문자열의 길이에 대한 언급이 없지만 아무리 길어봤자 O(n) 안에 안풀리는 정도의 길이는 아닐 것 같았다
<br>
<br>
- 배열 스트림 처리를 알아두면 일일이 반복문으로 처리하던 걸 더 깔끔하게 쓸 수 있을 거 같다. 물론 코테에선 구현이 우선이고 깔끔함은 그 다음이지만.
<br>
<br>
10분
<br/>

[개별 - Yebin] 12939

---

programmers/70129/Yebin_70129.java

**[프로그래머스 70129 이진 변환 반복하기](https://school.programmers.co.kr/learn/courses/30/lessons/70129)**
<br>
<br>
- 이진수 문자열에서 0을 제거하고 그 문자열의 길이를 잰 것을 다시 이진수로 변환한다는 건 결국 1의 개수를 바로 세서 이진수로 변환하는 것과 같다
- 이걸 변환을 거친 문자열이 "1"이 될 때까지 반복
<br>
<br>
- 구현. 문자열 처리.
<br>
1. 1의 개수와 0의 개수를 셈
2. 1의 개수를 이진수 문자열로 변환
3. 변환 횟수와 제거한 0의 개수 갱신
4. 1~3을 문자열이 "1"이 될 때까지 반복
<br>
- 시간복잡도: 대충 생각했을 때 n = 150,000 이지만 0을 제거하면 길이가 기하급수적으로 떨어지므로 O(log n) 일거다 
<br>
<br>
- String 에 stream 처리하는거 제대로 알고 쓴게 아니라 '언젠가 봤던거 같은데...' 하면서 대충 감으로 써서 맞춤. java stream 에 제대로 알고 쓰고 싶음.
<br>
<br>
13분 
<br/>

[개별 - Yebin] 70129

---

programmers/42862/Minseon_42862.java

**[프로그래머스 42862번](https://school.programmers.co.kr/learn/courses/30/lessons/42862)**
<br>
<br>
- 체육복이 있는 사람만 체육 수업을 들을 수 있고 도난당해서 체육복이 없는 사람은 여분의 체육복이 있는 앞뒤 번호 사람에게 빌릴 수 있음. 
- 여분의 체육복이 있는 사람도 도난당할 수 있음.
- 체육 수업을 들을 수 있는(체육복을 가지고 있는) 최대 학생 수를 구하는 문제.
<br>
<br>
그리디와 단순 구현 그 사이 어딘가.
<br>
전체 학생 수가 최대 30명으로 적기 때문에 단순하게 풀어도 될 것 같았다.
모두가 처음에는 체육복을 한 벌씩 가지고 있다고 가정해서 1로 초기화한다.
도난당한 학생은 해당 인덱스에서 -1, 여분이 있는 학생은 해당 인덱스에서 +1
최종적으로 반복문을 돌며 체육복이 없는 학생은 앞뒤 학생 중 여분이 있는 학생에게서 체육복을 가져온다.
<br>
시간복잡도: 최악의 경우도 O(n)
공간복잡도: 원소가 최대 30개인 1차원 배열만 씀
<br>
<br>
<br>
<br>
소요시간: 약 15분
<br/>

[공통 - Minseon] 42862

---

baekjoon/1912/Minseon_1912.java

**[백준 1912번](https://www.acmicpc.net/problem/1912)**
<br>
<br>
- n개의 정수로 이루어진 수열이 주어지면 연속된 수를 선택해서 구할 수 있는 합 중 가장 큰 합을 구하는 문제.
- 수는 1개 이상 선택해야 함.
<br>
<br>
DP
<br>
- dp[i]를 i번째가 마지막인 연속합 중 가장 큰 값으로 정의한다.
- dp[i] = max(numbers[i], dp[i-1] + numbers[i])
<br>
O(n)
<br>
<br>
<br>
<br>
소요 시간 : 약 15분
<br/>

[개별 - Minseon] 1912

---

baekjoon/16401/Minseon_16401.java

**[백준 16401번](https://www.acmicpc.net/problem/16401)**
<br>
<br>
- M명의 조카가 있고 N개의 과자가 있을 때, 조카 1명에게 줄 수 있는 막대 과자의 최대 길이를 구하는 문제.
- 과자의 길이는 1이상이고 정렬된 상태로 주어지지 않는다.
<br>
<br>
이진탐색
<br>
- mid를 나눠주는 막대 과자의 길이로 정의한다.
- snacks[i]를 mid로 나눴을 때 몇 명에게 나눠줄 수 있는지 계산해서 M보다 크거나 같으면 left = mid + 1, 작으면 right = mid - 1
<br>
이진탐색의 시간복잡도는 O(logN). 이진탐색 안에 for문이 있으므로 O(N*logN).
<br>
<br>
문제 조건을 잘못 이해해서 정렬이 된 상태로 주어지는 줄 알았는데 알고보니 아니었다.
<br>
<br>
소요 시간 : 약 30분
<br/>

[개별 - Minseon] 16401

---

programmers/81301/Suhwa_81301.java

**[ 81301번](https://school.programmers.co.kr/learn/courses/30/lessons/81301)**
<br>
<br>
각 문자열과 숫자를 대치하는 문제
<br>
<br>
구현
<br>
그냥 주어진 문자열이 문자가 있을때 replace
<br>
contain(O(n))쓰고 replace(O(n))
O(n)
<br>
<br>
갑자기 집 인터넷이 안되서 따로 풀게된것
<br>
<br>
<br/>

[ 공통 - Suhwa ] 81301

---

programmers/42626/Suhwa_42626.java

**[42626번](https://school.programmers.co.kr/learn/courses/30/lessons/42626)**
<br>
<br>
순간순가 최소값을가져와야하는문제
<br>
<br>
힙
이유 : 순간마다 최소값만 필요해서 전체 정렬보다 힙으로만 쓰자
<br>
최소힙생성
1. K보다 큰지작은지, 최소힙크기확인
2. 최소값2개꺼내서 섞고 넣기
다시 1 반복
<br>
힙사용 -> O(logn)
<br>
<br>
딱히... 갑자기 집인터넷안되서 계속 밖에서 공부해야했음.....
<br>
<br>
<br/>

[공통 - Suhwa ]  42626

---

programmers/82612/Minseon_82612.java

**[프로그래머스 82612번](https://school.programmers.co.kr/learn/courses/30/lessons/82612)**
<br>
<br>
- 놀이기구를 탈 때마다 이용료를 내는데, 그 이용료는 탄 횟수만큼 배가 됨.
- 필요한 이용료보다 가지고 있는 돈이 적으면 그 차이 return, 그렇지 않으면 0 return
<br>
<br>
구현
<br>
반복문을 이용해서 늘어나는 이용료를 계산한다.
<br>
O(n)
<br>
<br>
위클리 챌린지 Lv.1 문제를 풀었는데 체감상 백준 실버 4~3정도 난이도인 것 같아서 이것보다 높은 난이도의 문제를 도전해봐야겠다.
<br>
<br>
소요 시간 : 약 10분
<br/>

[개별 - Minseon] 82612

---

programmers/87377/Minseon_87377.java

**[프로그래머스 87377번](https://school.programmers.co.kr/learn/courses/30/lessons/87377)**
<br>
<br>
- Ax + By + C = 0으로 표현할 수 있는 n개의 직선의 교점을 '.'으로 이루어진 좌표평면에 '*'로 그려서 출력하는 문제.
- 교점은 정수로만 이루어진 교점만 해당된다. ex) (5, 3) -> (O), (0.5, 2) -> (X)
- 좌표평면의 크기는 교점을 모두 포함할 수 있는 최소 사각형이어야 한다.
<br>
<br>
완전탐색(교점 구하기) + 구현(좌표평면 그리기)
<br>
- Point 클래스를 만들어서 좌표를 저장.
- 단계를 나누어서 최종 격자판을 출력한다.
- <1단계> 교점 구하기 + 중복 교점 처리
- 교점을 구하는 공식을 이용해서 두 직선의 교점의 좌표를 구한다.
- 직선 Ax + By + E = 0과 Cx + Dy + F = 0의 교점은 x = BF-ED / AD-BC, y = EC-AF / AD-BC
- AD-BC == 0인 경우, 두 직선은 평행하므로 continue
- stream().distinct()를 이용해 중복 교점을 처리한다.
- <2단계> 좌표평면 크기 구하기
- 교점을 이용해서 최소 사각형 형태의 좌표평면을 구한다.
- <3단계> 교점 좌표에 별 찍기
-  StringBuilder를 이용해서 해당 좌표에 '.' -> '*'로 교체
<br>
시간복잡도는 모든 직선의 교점을 …

[개별 - Minseon] 87377

---

programmers/72411/Minseon_72411.java

**[프로그래머스 72411번](https://school.programmers.co.kr/learn/courses/30/lessons/72411)**
<br>
<br>
- 손님들이 각자 단품 메뉴들을 주문한 내역을 토대로 가장 많이 주문한 단품 조합을 구성하여 코스 요리 메뉴를 만드는 문제.
- 코스 요리 메뉴의 개수는 course 배열에서 주어지는 개수를 따른다.
- 코스 요리 메뉴에 포함하는 기준은 2번 이상 주문된 조합이어야 하고, 주문 횟수가 같으면 모두 포함한다.
<br>
<br>
백트래킹+dfs, 해시
<br>
- 주어진 단품 메뉴 구성으로 주어진 단품 메뉴 개수에서 가능한 모든 코스 요리 조합을 만든 다음 HashMap을 이용해 메뉴의 빈도수를 센다. 
- 빈도수가 2 이상인 가장 높은 빈도수를 가지는 메뉴를 최종 메뉴 리스트에 넣는다.
<br>
orders의 길이를 n, course의 길이를 k라고 하면 combination 메소드의 시간복잡도는 최악의 경우 O(2^n)이 되므로 최종적으로는 O(n * k * 2^n)이 된다.
<br>
<br>
문제를 제대로 분석하지 못해서 계속 놓치는 조건들이 있었다.
아니 이게 어떻게 Lv.2
<br>
<br>
소요 시간 : 약 1시간 20분
<br/>

[공통 - Minseon] 72411

---

programmers/12977/Minseon_12977.java

**[프로그래머스 12977번](https://school.programmers.co.kr/learn/courses/30/lessons/12977)**
<br>
<br>
- 주어진 숫자 배열에서 중복없이 3개를 골라서 더한 값이 소수인지 판별하는 문제.
<br>
<br>
완전탐색
<br>
- 조합에 들어가는 원소의 개수가 3개로 고정되어 있기 때문에 따로 함수를 구현하지 않고 반복문으로 조합을 만든다.
- 소수 판별 방법은 2~n-1로 하나하나 다 나눠봐서 나머지가 0인 경우가 나오면 소수가 아닌 수이고, 그렇지 않으면 소수이다.
<br>
시간복잡도는 nums 배열의 크기를 k라고 하면 조합을 만드는데 O(k^3), 소수를 판별하는데 O(n)이므로 O(k^3*n)이지만 n이 1000이하의 수라는 조건이 있어서 완전탐색으로 풀어도 괜찮다고 생각했다.
<br>
<br>
<br>
<br>
소요 시간 : 약 10분
<br/>

[개별 - Minseon] 12977 

---

programmers/81301/Minseon_81301.java

**[프로그래머스 81301번](https://school.programmers.co.kr/learn/courses/30/lessons/81301)**
<br>
<br>
- 영단어와 숫자가 섞인 문자열이 주어지면 영단어를 대응되는 숫자로 바꾸어서 원래 숫자를 구하는 문제.
<br>
<br>
구현+해시맵
<br>
해시맵을 이용해서 영단어(키)와 숫자(값)을 저장하고 replace 메소드를 이용해서 문자열을 해당하는 숫자로 치환한다.
<br>
O(N)
<br>
<br>
<br>
<br>
소요 시간 : 약 10분
<br/>

[공통 - Minseon] 81301

---

programmers/42626/Minseon_42626.java

**[프로그래머스 42626번](https://school.programmers.co.kr/learn/courses/30/lessons/42626)**
<br>
<br>
- 스코빌 지수가 가장 작은 순서대로 요리를 나열해서 모든 요리의 스코빌 지수가 원하는 스코빌 지수보다 높을 때까지 가장 낮은 두 요리를 섞어 더 매운 음식을 만드는 최소 횟수를 구하는 문제.
- 섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2)
- 끝까지 원하는 스코빌 지수보다 높은 요리를 만들지 못하면 -1 리턴.
<br>
<br>
우선순위 큐(힙)
<br>
- 우선순위 큐를 이용해서 스코빌 지수가 낮은 순서대로 정렬한 후, 가장 작은 요리의 스코빌 지수가 K보다 작으면서 우선순위 큐의 크기가 1보다 클 때까지 요리를 섞는다.
- 우선순위 큐의 크기가 1이 되었을 때 그 요리의 스코빌 지수가 K보다 작으면 -1 리턴
<br>
O(N*logN)
<br>
<br>
- 반복문의 종료조건을 처음에 가장 낮은 스코빌 지수가 K보다 큰 지를 고려하지 않고 우선순위 큐의 크기만을 고려해서 거기서 시간이 오래 걸렸다.
<br>
<br>
소요 시간 : 약 20분
<br/>

[공통 - Minseon] 42626

---

programmers/42839/Minseon_42839.java

**[프로그래머스 42839번](https://school.programmers.co.kr/learn/courses/30/lessons/42839)**
<br>
<br>
- 주어진 문자열로 만들 수 있는 모든 숫자 중 소수인 숫자의 개수를 구하는 문제.
- 앞에 0이 있어도 0이 없는 문자열과 같은 수로 취급한다. ex) "011" == "11"
<br>
<br>
완전탐색
<br>
- 순열을 이용해서 1~주어진 문자열의 길이만큼 선택한 모든 순열을 구한다.
- 문자열을 만드는 데 StringBuilder를 활용했다.
- 중복된 문자열이 나올 수 있으므로 List가 아닌 Set에 저장한다.
- 소수를 판별하는 함수는 시간 절약을 위해 n의 제곱근까지만 나눈다.
<br>
순열을 구하는 문제이므로 시간복잡도는 O(n!). 다행히 n <= 7이라는 조건이 있어서 마음편히 순열을 쓸 수 있었다.
<br>
<br>
- 알고리즘 자체는 쉬운 문제인데 정답률이 왜 낮지 했는데 예외 케이스가 자꾸 발견돼서 그것을 해결하는데 시간이 오래 걸렸다. 2를 고려하지 않았다거나, 제곱근을 고려하지 않았다거나, 0이 여러개가 들어있는 케이스를 고려하지 않았다거나...
<br>
<br>
소요 시간 : 약 1시간
<br/>

[개별 - Minseon] 42839

---

programmers/12946/Yebin_12946.java

**[프로그래머스 12946 하노이의 탑](https://school.programmers.co.kr/learn/courses/30/lessons/12946)**
<br>
<br>
- 일단 쓸 수 있는 단계 까지 하노이의 탑 풀이를 씀
- 규칙은 그림 참고
<br>
<br>
- 재귀
<br>
1. 현재 기둥을 from, 목표 기둥을 to, 나머지 기둥을 mid라 하면 
2. 원판 n-1까지를 from -> mid
3. 원판 n을 from -> to
4. 원판 n-1까지를 mid -> to
5. 2, 4를 n = 1 이 될 때 까지 재귀 
<br>
- 시간복잡도: 재귀함수를 이용하고 재귀를 들어가는 것을 트리처럼 생각해보면 가지가 두 갈래로 뻗어나가므로 O(2^n)이라 생각함. 지수함수라 숫자가 커질수록 기하급수적으로 오래 걸리겠지만 n = 15 안에는 풀리는 문제를 줬을거라 내맘대로 짐작하고 풀었음...
- 공간복잡도: 재귀함수를 이용하면 스택 메모리를 사용함. n-1번 호출해서 깊이가 n-1이라 생각했음. 그래서 공간복잡도는 O(n).
<br>
<br>
- 재귀에 대한 이해가 부족해서 규칙을 발견해도 그걸 코드로 빠르게 구현하지 못한 점. 더 쉬운 문제로 많이 연습해야겠다고 생각함.
<br>
<br>
<br/>

[공통 - Yebin] 12946

---

programmers/72411/Yebin_72411.java

**[프로그래머스 72411번 메뉴 리뉴얼](https://school.programmers.co.kr/learn/courses/30/lessons/72411)**
<br>
<br>
- 주문을 코스 개수 대로 조합을 만들고 카운트하면 됨
<br>
<br>
- 완전 탐색인데 조합을 곁들인... 
<br>
1. 함께 주문한 메뉴를 코스 개수 대로 조합을 만든다.(중복을 없애기 위해 주문 정렬 필요)
2. 조합을 키로 하는 맵에 개수 저장
3. 코스 개수 벼로 가장 많이 시킨 조합을 찾음
4. 마지막으로 사전 오름차순으로 정렬
<br>
- 시간복잡도: 다른 반복문도 있지만 이미 조합 만드는데 O(2^n) 그치만 코스 길이가 최대 10이므로 완탐 해도 된다고 생각했다.
- 공간복잡도: 조합의 최대 개수가 10C2 = 90개 이니까 괜찮지 않을까.. 
<br>
<br>
- 코스 개수 별로 가장 많이 주문된 걸 골라야 하는 조건을 못보고 부분집합인거 제거한다고 30분 정도 허비함
<br>
<br>
<br/>

[공통 - Yebin] 72411

---

programmers/43163/Suhwa_43163.java

**[42613번](https://school.programmers.co.kr/learn/courses/30/lessons/43163)**
<br>
<br>
BFS를 통해 최단 변화단계를 세는 문제
<br>
<br>
BFS
<br>
BFS를 통해 '이미 방문하지 않은 원소중, 기준단어와 알파벳이 한개만틀린글자'를 탐색해 나가기
<br>
O(n) + O(nm)  ->Bfs의 시간복잡도만큼
<br>
<br>
1. 최단거리세기
처음에는 visit 배열을 새로 생성해 visit 배열에 방문체크 + 경로체크하려고함
그렇게 하면 bfs의 리턴값이 애매해짐. 큐에 문자열을 넣었는데, return 할때 words에서 현재 문자열이 어떤 index인지 한번더 찾아야함
-> 해결 : Node라는 새로운 내부 클래스를 만들어서, 큐에 ( 문자열, begin에서 해당문자열까지 단계수) 형태로 저장
2. 테스트 케이스 3 실패
이유 : begin "aab", target "aba" ["abb","aba"]
기존 로직은 문자한개가 비교할 문자열에 포함되었는지 여부 판단 -> 문자의 위치도 중요함 -> 비교할 문자열 2개를 둘다 배열형태로 만들어 한자리씩 비교
<br>
<br>
<br/>

[공통 - Suhwa] 42613

---

programmers/17680/Suhwa_17680.java

**[17680번](https://school.programmers.co.kr/learn/courses/30/lessons/17680)**
<br>
<br>
간단한 캐시를 구현하여 주어진 리스트를 캐시에 검색해보는 문제
<br>
<br>
LRU 사용 -> 최근 검색한것을 가장 중요도가 높은 것으로 선택 
즉 최근 검색한 내용을 앞자리에 추가해야함
-> 배열은 맞지 않음
중간 추가, 중간 삭제에 성능이 좋은 연결리스트사용
<br>
연결리스트로 캐시사이즈만큼의 캐시를 구현해, LRU 방식으로 보기
<br>
연결리스트 특성상 추가, 삭제(특히 index가 주어진 삭제)는 O(1)대
캐시에 저장되었는지 확인하는 contains가 O(n)임.
이때 n은 캐시사이즈 (캐시사이즈에 대한 조건은 별로 없네옹)
<br>
<br>
없음
<br>
<br>
<br/>

[공통 - Suhwa] 17680

---

programmers/77484/Suhwa_77484.java

**[77484번](https://school.programmers.co.kr/learn/courses/30/lessons/77484)**
<br>
<br>
Lottos에서 0이아닌 숫자가 win_nums에서 몇개나 맞았는지만 세면 되는 문제
<br>
<br>
아마... 구현?
<br>
Lottos에서 0이아닌 숫자가 win_nums에서 몇개나 맞았는지만 세면 되는 문제
<br>
2중 for문이지만 로또 숫자가 6자리라서 최대 36이라 괜찮다고 생각
<br>
<br>
<br>
<br>
<br/>

[개별 - Suhwa] 77484

---

programmers/77485/Suhwa_77485.java

**[77485번](https://school.programmers.co.kr/learn/courses/30/lessons/77485)**
<br>
<br>
위의 그림대로 한칸씩 회전하는 문제
<br>
<br>
구현
<br>
직사각형의 테두리에 한칸씩만 회전하는 문제 -> 회전할 직사각형 4개의 변이 각기 다른 패턴을 가질것
<br>
최악의 경우 O(n), 회전할 직사각형의4변만 값을 바꾸느라 돎
<br>
<br>
<br>
<br>
<br/>

[개별 - Suhwa] 77485

---

programmers/43163/Minseon_43163.java

**[프로그래머스 43163번](https://school.programmers.co.kr/learn/courses/30/lessons/43163)**
<br>
<br>
- begin에서 words에 있는 단어로 한 단계에 하나의 알파벳만 바뀌도록 변환하여 target으로 만드는 최소 횟수를 구하는 문제
- words에 있는 단어의 길이는 모두 같고, 길이는 3이상 10이하이다.
- 변환할 수 없는 경우 0 리턴.
<br>
<br>
dfs
<br>
- 한 알파벳씩 차이나는 단어를 찾아서 인접리스트를 만든다.
- words를 순회하며 begin과 한 알파벳이 차이나면 dfs로 target 단어로 변환한다.
- 한 알파벳이 차이나는지 확인하는 메소드 isDifferent를 만든다.
<br>
dfs를 재귀함수로 구현하여 최악의 경우 O(n!)의 시간복잡도를 가지므로 최종 시간복잡도는 O(n^2*n!)이다.
<br>
<br>
문자열이 같은지 확인하는 과정에서 자바의 String type은 == 연산자가 아닌 equals 메소드를 이용해야 한다는 것을 늦게 발견해서 여기서만 30분을 추가로 더 썼다.
<br>
<br>
소요 시간 : 1시간
<br/>

[공통 - Minseon] 43163

---

programmers/12939/Minseon_12939.java

**[프로그래머스 12939번](https://school.programmers.co.kr/learn/courses/30/lessons/12939)**
<br>
<br>
공백으로 구분된 숫자들로 이루어진 문자열에서 최솟값과 최댓값을 구하는 문제
<br>
<br>
구현
<br>
문자열을 공백을 기준으로 split해서 배열을 만든 다음 크기 순으로 정렬해서 첫번째 원소와 마지막 원소를 출력한다.
<br>
정렬의 시간복잡도와 같으므로 O(NlogN)
<br>
<br>
<br>
<br>
소요 시간 : 5분
<br/>

[개별 - Minseon] 12939

---

programmers/12911/Minseon_12911.java

**[프로그래머스 12911번](https://school.programmers.co.kr/learn/courses/30/lessons/12911)**
<br>
<br>
n보다 크고 2진수로 변환했을 때 n을 2진수로 변환한 수와 1의 개수가 같은 가장 작은 수를 구하는 문제.
<br>
<br>
완전탐색
<br>
- n+1부터 조건에 맞는 수를 찾는다.
- 이때, 2진수로 변환했을 때 1의 개수를 세는 코드는 메소드로 따로 분리한다.
<br>
최악의 경우 O(n)
<br>
<br>
<br>
<br>
소요 시간 : 5분
<br/>

[개별 - Minseon] 12911

---

programmers/132267/Minseon_132267.java

**[프로그래머스 132267번](https://school.programmers.co.kr/learn/courses/30/lessons/132267)**
<br>
<br>
콜라 빈 병 a개를 가져다주면 콜라 병 b개를 준다고 할 때 빈 병 n개를 갖다주면 총 몇 개의 콜라병을 받을 수 있는지 계산하는 문제.
<br>
<br>
구현
<br>
문제에서 제시한 계산식과 조건을 그대로 코드로 적용한다. 이때, n은 빈 병의 개수, answer는 받은 콜라병의 개수이다.
<br>
O(n)
<br>
<br>
처음에 일반화된 문제라는 것을 제대로 못보고 무조건 빈 병 2개에 콜라 1병이라고 생각하고 풀어서 시간이 살짝 더 걸렸다.
<br>
<br>
소요 시간 : 10분
<br/>

[개별 - Minseon] 132267

---

programmers/17680/Minseon_17680.java

**[프로그래머스 17680번](https://school.programmers.co.kr/learn/courses/30/lessons/17680)**
<br>
<br>
LRU를 이용해서 cache hit가 발생하면 1, cache miss가 발생하면 5가 걸릴 때, 총 실행 시간을 계산하는 문제.
<br>
<br>
연결 리스트를 이용한 LRU 구현
<br>
- LinkedList를 사용해서 캐시 구현
- cacheSize보다 적게 들어있을 때
- miss면 add하고 +5, hit면 remove -> add -> +1
- cacheSize만큼 들어있을 때
- miss면 cache의 첫번째 노드(가장 옛날에 참조된 노드) remove -> add -> +5, hit면 remove -> add -> +1
<br>
O(n)
<br>
<br>
대소문자 관련된 조건을 늦게 봤다.
<br>
<br>
소요 시간 : 약 30분
<br/>

[공통 - Minseon] 17680

---

programmers/43163/Yebin_43163.java

**[프로그래머스 43163번 단어변환](https://school.programmers.co.kr/learn/courses/30/lessons/43163?language=java)**
<br>
<br>
- 이렇게 한 글자만 다른 단어를 건너서 타깃을 찾음
- 한 글자만 다른 단어를 어떻게 찾아서 넘어가냐가 관건
<br>
<br>
- 깊이/너비 우선 탐색 
<br>
1. `target`이 `words`에 없으면 0
2. 큐에 Class(단어, 카운트)를 넣음
3. 큐가 빌 때까지 `words` 리스트를 돌며 아직 큐에 안넣은 단어 중 한 글자만 다른 걸 큐에 넣고 방문 처리
4. 찾으면 해당 카운트를 반환, 아니면 0을 반환
<br>
- 시간복잡도 : `words`를 계속 순회하지만 길이가 50이고 단어 하나도 최대 10이니까 글자 하나하나를 바꾼다 해도 500 정도의 계산이면 될 것 같다. 대충 O(n^2) 인 셈이지만 n이 50으로 작아서 괜찮겠다는 말
- 공간복잡도 : 재귀도 안하고 큐만 사용하니까 메모리 초과는 고민하지 않았다
<br>
<br>
단어와 카운트를 함께 저장하는 클래스를 만들면 되는 걸 파이썬 하던 버릇대로 리스트에 꾸겨넣을 생각만 하다가 조금 오래걸렸다
<br>
<br>
50분
<br/>

[공통 - Yebin] 43163

---

programmers/17680/Yebin_17680.java

**[프로그래머스 17680번](https://school.programmers.co.kr/learn/courses/30/lessons/17680)**
<br>
<br>
- LRU 알고리즘 : 최신인 것이 우선이다 -> 가장 오래된 페이지를 버림
- 캐시가 0일 수 도 있다는 것. 이 경우를 먼저 처리한다.
- 캐시로 쓸 자료구조는 순서대로 정렬이 가능하면서 검색이 빨라야 한다. 
- ~그래서 Deque를 쓰기로 함. Deque는 Queue와 달리 앞뒤로 다 넣고 뺄 수 있는 구조이다.~
- 생각해보니 나는 Queue를 써도 차이가 없음. 그래서 Queue로 바꿈.
<br>
<br>
- 알고리즘이라기 보단 자료구조 선택에 가까운 문제
<br>
1. 캐시가 0이면 모든 검색에 5s 걸린 결과 리턴
2. 캐시에 있는지 찾음
3. 캐시에 있으면 1s, 캐시에서 도시를 빼고 다시 집어넣음으로써 최신 검색이 가장 뒤로 오게 한다
4. 캐시에 없으면 5s, 캐시에서 가장 오래된 도시를 제거하고 새 검색을 넣는다
<br>
- 시간복잡도: 일단 도시가 100,000개나 되지만 이건 한번쯤은 순회를 해야 하는 것이므로 줄일 수 없음. 문제는 contains()라고 생각했는데 그래봤자 캐시 크기가 최대 30이므로 contains()가 O(n)이어도 문제될 건 없다고 생각했다. 
- 공간복잡도: 쓰는 자료구조는 큐 뿐이고 재귀도 없어서 메모리 부족은 없을거라 생각했다.
<br>
<br>
- 자바 컬렉션을 …

[공통 - Yebin] 17680

---

programmers/12973/Yebin_12973.java

**[프로그래머스 12973번 짝지어 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12973)**
<br>
<br>
- 2개씩 짝지어 제거하는 문제
- 괄호를 짝짓는 것과 비슷하다
- 스택 구조를 생각하면 편하다. 
<br>
<br>
- 스택 자료구조
<br>
1. 스택이 비어있으면 문자 넣기
2. 스택의 맨 위와 같으면 문자 제거
3. 같지 않으면 문자 넣기
4. 1~3을 반복하여 스택에 문자가 남아있으면 문자를 다 제거하지 못한 것
<br>
- 시간복잡도 : n = 1,000,000 인데 한 번만 순회하므로 O(n)
- 공간복잡도 : Deque를 사용하고 최악의 경우 문자열의 절반을 저장하므로 O(n)
<br>
<br>
❌ 
<br>
<br>
19분 
| 중첩 if | 중첩 없이 continue |
|---|---|
|<img width="448" alt="스크린샷 2023-11-03 오후 9 43 51" src="https://github.com/Algorithm-SQL-Study/Algorithm-SQL-Study/assets/69137469/b6fb736b-f7d4-4d24-aa0b-094779f0574a">|<img width="505" alt="스크린샷 2023-11-03 오후 9 47 52" …

[개별 - Yebin] 12973

---

programmers/42842/Yebin_42842.java

**[프로그래머스 42842번 카펫](https://school.programmers.co.kr/learn/courses/30/lessons/42842)**
<br>
<br>
- 카펫 가로 m, 세로 n 
- m >= n
- m, n 최소 3
- m * n = Y + B
- 격자 갯수 조건
- Y = (m-2) * (n-2)
- B = 2m + 2(n-2)
<br>
<br>
- 완전 탐색
- n = 3부터 가능한 모든 n을 탐색
<br>
1. n을 기준으로 mn = Y + B 에 맞는 m을 찾음
2. B = 2m + 2(n-2)에 맞는지 확인 
<br>
- 시간복잡도 : 세로 길이를 최악의 경우 3 ~ mn/2 정도 계산할 것이므로 O(n)
- 공간복잡도 : 딱히 사용하는 자료구조나 재귀가 없으므로 O(1)
<br>
<br>
- 반복문이 끝나는 조건을 고민하느라 시간을 많이 썼다. 근데 사실 무조건 카펫이 완성되는 brown, yellow 를 주므로 끝나는 조건은 mn/2 이든 mn 이든 그 전에 끝난당.. 
<br>
<br>
45분
<br/>

[개별 - Yebin] 42842

---

programmers/12981/Yebin_12981.java

**[프로그래머스 12981번 영어 끝말잇기](https://school.programmers.co.kr/learn/courses/30/lessons/12981)**
<br>
<br>
- 문자열만 잘 처리하면 되는 구현 문제
- 이전의 단어들을 저장하고 검색하기 위해 HashSet을 사용. 검색이 빠르다고!
<br>
<br>
- 구현
- 문자열 처리
<br>
1. 이미 나온 단어이거나 이전 단어의 끝말을 잇지 않았으면 끝
2. 사람 순서를 한바퀴 돌 때마다 라운드를 +1 해줘야 함 
<br>
- 시간복잡도 : words가 100개 뿐이고 HashSet의 contains 검색 속도는 O(1)이므로 시간은 충분
- 공간복잡도 : Set 자료구조 사용 O(n)
<br>
<br>
❌ 
<br>
<br>
14분
<br/>

[개별 - Yebin] 12981

---

programmers/12926/Minseon_12926.java

**[프로그래머스 12926번](https://school.programmers.co.kr/learn/courses/30/lessons/12926)**
<br>
<br>
문자열을 구성하는 알파벳을 n만큼 밀어서 암호문을 만드는 문제. 이때 z -> a, Z -> A로 이동
<br>
<br>
문자열 구현
<br>
아스키코드를 이용해서 소문자 따로, 대문자 따로 처리한다.
<br>
O(n)
<br>
<br>
<br>
<br>
소요 시간 : 12분
<br/>

[개별 - Minseon] 12926

---

programmers/131701/Minseon_131701.java

**[프로그래머스 131701번](https://school.programmers.co.kr/learn/courses/30/lessons/131701)**
<br>
<br>
원형 수열의 연속 부분 수열 합이 될 수 있는 모든 수의 개수를 구하는 문제.
<br>
<br>
완전탐색
<br>
- 원형 연결 리스트 class를 만들어서 head부터 순서대로 부분 수열의 길이마다 만들 수 있는 모든 연속 부분 수열합을 구한다.
- 구한 연속합을 HashSet에 넣어 중복을 제거한 후, HashSet의 크기를 출력한다.
<br>
부분수열합을 구할 때 for문이 2개, while문도 원소의 개수만큼 실행되므로 O(n^3)
<br>
<br>
<br>
<br>
소요 시간 : 23분
<br/>

[개별 - Minseon] 131701

---

programmers/1844/Minseon_1844.java

**[프로그래머스 1844번](https://school.programmers.co.kr/learn/courses/30/lessons/1844)**
<br>
<br>
시작 지점에서 상대 팀 진영에 도달하는 최단 거리를 구하는 문제. 도달할 수 없으면 -1 리턴.
<br>
<br>
bfs
<br>
- bfs를 이용해서 최단거리를 구한다.
- 이때, Node 클래스를 만들어서 좌표와 depth를 저장한다.
<br>
O(n*m)
<br>
<br>
<br>
<br>
소요 시간: 28분
<br/>

[개별 - Minseon] 1844

---

programmers/77486/Yebin_77486.java

**[프로그래머스 77486 다단계 칫솔 판매](https://school.programmers.co.kr/learn/courses/30/lessons/77486)**
<br>
<br>
- 문자열 검색을 많이 해야 한다. HashMap을 쓰기로. 검색에 O(1) 걸린다.
- 무조건 위에 있는 사람에게만 주면 되므로 <하위, 상위> 사람 형태로 그래프를 저장해야겠다. 
- center의 몫은 답에 포함되지 않기 때문에 따로 저장하지 않음.
testcase 11, 12, 13 틀린 후
- DFS를 끊어낼 방법을 찾아야 한다. 
- 처음엔 credit을 기준으로 끊어내려고 했다. 
- credit이 결국 다음 재귀의 money가 되니까. 
- credit < 10 이면 10%를 해도 1이 안되니까 이렇게 멈추려고 했는데 예상과 다름. 
- 그래서 재귀를 한 단계 더 하더라도 money로 끊음.
- money 가 0 이하가 되면 재귀를 그만하도록. 
<br>
<br>
- DFS 
<br>
1. 다단계 피라미드를 HashMap에 <하위, 상위> 사람 형태로 저장
2. 각 사람의 수익을 저장할 HashMap도 초기화
3. 상위의 사람에게 크레딧을 전달하는 방식으로 dfs 
4. 수익률을 답에 맞는 형태로 가공해서 반환 
<br>
- 시간복잡도 : 재귀는 보통 O(n log n) 으로 알고 있고 검색이 O(1) 이니까 O(n log n);
- 공간복잡도 : 
<br>
<br>
- dfs를 끊을 조건을 …

[공통 - Yebin] 77486

---

programmers/12914/Yebin_12914.java

**[프로그래머스 12914번 멀리뛰기](https://school.programmers.co.kr/learn/courses/30/lessons/12914)**
<br>
<br>
- 1칸 또는 2칸 씩 움직여서 목표로 하는 칸에 도달하는 문제
- n칸에 도달하는 방법이 n-1칸에서 1칸 멀리 뛰기를 하는 방법과 n-2칸에서 2칸 멀리 뛰기를 하는 방법이 있다
- 목표가 일단 프로그래머스 level2 다 풀기여서 풀었지만 레벨이 잘못된 것 같은 문제였다 
<br>
<br>
- Dynamic programming
<br>
1. n개의 칸에 도달하는 방법을 저장하는 배열 생성
2. n-1 칸에서 오는 방법과 n-2 칸에서 오는 방법을 더하고 저장할 때마다 %1234567
<br>
- 시간복잡도 : n칸이라면 dp를 n번 계산하므로 O(n)
- 공간복잡도 : n개의 칸에 대한 방법을 저장하는 배열 말고는 쓰는 자료구조가 없으므로 O(n) 
<br>
<br>
❌ 
<br>
<br>
10분 
<br/>

[개별 - Yebin] 12914

---

programmers/12980/Yebin_12980.java

**[프로그래머스 12980번](https://school.programmers.co.kr/learn/courses/30/lessons/12980)**
<br>
<br>
- 점프와 순간이동인데 순간이동은 배터리가 안든다는 설명을 보고 이거 딱 우선순위큐 쓰면 되는 BFS 문제네! 하고 풀었음
- 근데 효율성 테스트에서 전부 실패
- 그래서 조건을 다시 보니 N이 최대 10억이었다. 이건 절대 그냥 BFS로 푸는게 아니구나 생각하고 테케를 다시 그려봄.
- 그려보니까 홀수칸이면 반드시 +1 해서 도달해야 하고 짝수칸이면 짝수칸이면 *2 해서 도달해야 최적의 경로가 된다는 것을 알게됨
- 0 -> n 이 아니라 n 에서부터 2로 나누거나 1을 빼서 0을 만들어가는 방법으로 최적의 경로를 구했다
<br>
<br>
- BFS 인줄 알았으나 Greedy
<br>
1. 현재 수가 홀수면 -1, 짝수면 / 2 를 해서 0까지 만든다
2. -1 할때만 배터리를 1씩 증가시킨다
<br>
- 시간복잡도 : x가 연산 횟수라면 2^x = n 이라 생각해서 O(log n)
- 공간복잡도 : 배터리 변수 빼곤 따로 쓰는거 없으므로 O(1)
<br>
<br>
- 문제의 조건을 더 잘 보고 알고리즘을 선택하는게 좋겠다. 생각 없이 풀지 말자.
<br>
<br>
45분 
<br/>

[개별 - Yebin] 12980

---

programmers/12985/Yebin_12985.java

**[프로그래머스 12985번 예상 대진표](https://school.programmers.co.kr/learn/courses/30/lessons/12985)**
<br>
<br>
- 이렇게 그려봤더니 다음 라운드에서 다시 배정받는 숫자가 같은 숫자끼리 이번 라운드에서 게임을 하게 된다는 규칙을 발견
- 다음 라운드에서 배정받을 숫자는 (현재 / 2) + (현재 % 2) 로 구할 수 있다
<br>
<br>
- 구현
<br>
1. 다음 라운드에서 배정받을 숫자를 계산
2. a, b 가 같아질 때의 라운드를 반환
<br>
- 시간복잡도 : 맨 위 결승에서 만나게 된다면 트리의 높이와 같음 2^h - 1 = n 이므로 O(log n)
- 공간복잡도 : 따로 자료구조를 쓰는게 없어서 O(1)
<br>
<br>
❌ 
<br>
<br>
10분 
<br/>

[개별 - Yebin] 12985

---

programmers/118667/Suhwa_118667.java

**[118667번](https://school.programmers.co.kr/learn/courses/30/lessons/118667)**
<br>
<br>
큐에서 큐로 넣어지는것이기 때문에 일단 작업을 하나씩 하나보면 언젠가는 값이 도달가능
그러나 애초에 도달불가능한 값 판별이 중요 
절반으로 각 큐가 같은 값 불가능 케이스
1. 두 큐의 모든 수의 합이 2로 나누어지지 않는경우
`2. 모든큐의 모든 원소가 이동해도 같은 값 이 안되는경우
`이렇게 생각,
하지만!! 2번은 좀.... 어쩌다 맞은 느낌임... 아쉬운 점에 이어서 기술.
<br>
<br>
완전탐색 + 그리디
<br>
하나의 큐에서 데이터를 빼서 다른 큐에 넣는 작업을 할때마다 각 큐의 총합을 비교하여, 더작은 큐에 값을 넣어준다
<br>
일단 큐에서 넣고 빼는 것은 링크드리스트이기에 O(1)
처음 각 큐의 원소의 합 -> 2O(n) = O(n)
while의 의 반복개수는 최대 두원소개수의 합 +10임으로 ->O(n)
1 ≤ queue1의 길이 = queue2의 길이 ≤ 300,000
1 ≤ queue1의 원소, queue2의 원소 ≤ 109
이므로 시간복잡도, 저장 타입을 잘선택
<br>
<br>
음.....
사실 원래 -1 return 조건을 2로나누어지지 않는경우, 두 큐의 원소개수의 합보다 작업을 많이 할경우 이렇게 2가지로둠.
그랬더니 자꾸 case1에서만 실패가 일어나는 거임....
그래서 걍 임의로 두 원소개수의 …

[공통 - Suhwa] 118667

---

programmers/12946/Suhwa_12946.java

**[12946번](https://school.programmers.co.kr/learn/courses/30/lessons/12946)**
<br>
<br>
직접 n=5까지 해보니 재귀패턴이 보임.
<br>
<br>
재귀
<br>
n=1일때 : 출발지 원반 도착지로 옮김
n>1 :
-  출발지의 n-1 원반 경유지에 옮김
- 출발지에 있는 한 개의 원판을 도착지로 옮긴다.
- 경유지에 있는 n - 1개의 원판을 도착지로 옮긴다.
<br>
<br>
<br>
일일히 손으로 써가면서 재귀패턴을 찾는데 오래걸림...
<br>
<br>
<br/>

[공통 - Suhwa] 12946

---

programmers/77486/Suhwa_77486.java

**[77486번](https://school.programmers.co.kr/learn/courses/30/lessons/77486?language=java)**
<br>
<br>
자식 노드에서 부모노드로 루트까지 탐색해나가는 문제
<br>
<br>
그래프 탐색 -> 탐색이 중요
<br>
배열로했다가 시간초과떠서 해쉬맵사용. 해쉬맵은 검색의 시간복잡도가 O(1), 문제의 조건상 중복데이터가 없음
<br>
인덱스로 배열을 조회하는것은 O(1)의 시간복잡도 -> 부모노드가 enroll에서 어느 위치에 있는지 검색하는데 복잡도 키가 있다고 생각,
중복된 데이터가 없을때 O(1)의 검색효율을 보여주는 해쉬맵씀
<br>
<br>
아무리해도 케이스 11,12,13을 시간초과가 나옴....
고민하다가 그냥 다른사람 풀이를 봤음.
다른분 풀이를 보고, 10%의 절사가 한번 0 이되면 계속 루트로 탐색해봤자 0 이니 미리 리턴하는게 효율적이다는점을 알게됨.
이거정말.... 잔머리싸움,,,,
<br>
<br>
<br/>

[공통 - Suhwa ] 77486

---

programmers/172927/Minseon_172927.java

**[프로그래머스 172927번](https://school.programmers.co.kr/learn/courses/30/lessons/172927)**
<br>
<br>
- 세 종류의 곡괭이(다곡, 철곡, 돌곡)와 세 종류의 광물(다이아, 철, 돌)이 주어지고 각 곡괭이로 각 광물을 캘 때 드는 피로도는 아래와 같다.
- 광물은 한 번에 5개를 캘 수 있고, 주어진 순서대로 캐야 한다.
- 곡괭이는 아무거나 써도 되지만 곡괭이를 더 이상 쓸 수 없을 때까지 써야 한다.
- 주어진 곡괭이를 다 쓸 경우 더 이상 광물을 캘 수 없다.
- 다이아 곡괭이가 피로도 측면에서 가장 유리하기 때문에 다이아로 최대한 다이아를 많이 캐는 전략을 사용할 것이다.
<br>
<br>
그리디
<br>
- 주어진 광물을 순서대로 캐야 하므로 가지고 있는 곡괭이로 캘 수 있는 만큼 광물 배열을 자른다. 이때 광물 배열의 크기는 곡괭이의 개수 * 5가 된다.
- 광물 배열을 5개씩 묶어서 [다이아 개수, 철 개수, 돌 개수]로 작업 한 번에 캐야하는 광물의 개수를 저장하는 리스트를 만든다.
ex) ["diamond", "diamond", "diamond", "iron", "iron"]이면 [3, 2, 0]
- 해당 리스트를 다이아 > 철 > 돌의 개수로 우선순위를 두어 내림차순 정렬한다.
- 최소 피로도를 구해야 하므로 곡괭이는 다곡을 다 쓰면 철곡, 철곡을 다 쓰면 돌곡을 사용한다.
<br>
시간복잡도: 광물 개수 …

[개별 - Minseon] 172927

---

programmers/12914/Minseon_12914.java

**[프로그래머스 12914번](https://school.programmers.co.kr/learn/courses/30/lessons/12914)**
<br>
<br>
1칸 또는 2칸 점프가 가능한 멀리 뛰기에서 n까지 도달하는 방법의 수를 구하는 문제.
<br>
<br>
dp
<br>
- 현재 칸에 도달하는 방법의 수 = 1칸 전까지 도달하는 방법의 수 + 2칸 전까지 도달하는 방법의 수
- 점화식으로 표현하면 dp[i] = dp[i-1] + dp[i-2]
<br>
시간복잡도, 공간복잡도 모두 O(n).
<br>
<br>
long 배열이라 오버플로우가 발생하지 않을 줄 알고 dp[n]에 %12345678을 해줬는데 오버플로우가 발생해서 더하는 과정에서 %12345678을 해줬다. 이 에러를 찾는데 시간이 좀 걸렸다.
<br>
<br>
소요 시간 : 17분
<br/>

[개별 - Minseon] 12914

---

programmers/155651/Minseon_155651.java

**[프로그래머스 155651번](https://school.programmers.co.kr/learn/courses/30/lessons/155651)**
<br>
<br>
- [입실 시간, 퇴실 시간]으로 이루어진 문자열 배열로 예약 시간이 주어지면 배정할 수 있는 최소 객실을 구하는 문제
- 퇴실 이후에 10분 간 청소 시간이 있음
- 시간은 HH:MM 형식이고 자정을 넘지 않음
- 입실 시간은 항상 퇴실 시간보다 빠름
<br>
<br>
그리디 + 해시
<br>
- 입실 시간 순서대로 배열을 정렬한다. 문자열 사전순으로 해도 잘 정렬되므로 Arrays.sort()를 이용해서 입실 시간을 기준으로 그냥 정렬해도 된다.
- 방은 해시맵을 이용해서 방 번호와 이전 예약의 퇴실 시간을 저장한다.
- 이때, 퇴실 시간은 청소 시간을 포함한 값으로 한다. -> addCleaningTime() 메소드 구현
- 해시맵에 저장된 퇴실 시간과 입실 시간을 비교해서 예약이 가능한 방들 중 퇴실 시간이 가장 빠른 방 번호를 구한다. 이때, 예약 가능한 방이 없으면 새로운 방(방 개수+1번 방)을 배정한다.
- 퇴실 시간과 입실 시간 비교는 compareTo() 메소드를 활용하여 비교한다.
- 해당 방 번호의 퇴실 시간을 업데이트한다.
<br>
시간복잡도: 정렬하는데 O(NlogN), 방 배정 과정에서 최악의 경우 O(N * M)이므로 최종적으로 O(NlogN + N * M)
공간복잡도: 방 개수만큼의 해시맵 …

[공통 - Minseon] 155651

---

programmers/49189/Minseon_49189.java

**[프로그래머스 49189번](https://school.programmers.co.kr/learn/courses/30/lessons/49189)**
<br>
<br>
- 간선 정보와 노드의 개수가 주어지면 그래프를 만들어서 1에서 가장 먼 노드의 개수를 구하는 문제
<br>
<br>
bfs
<br>
- 각 노드까지의 최단거리를 모두 구해야 하므로 dfs보다는 bfs.
- 최단거리를 저장하는 배열을 만들어서 거리를 저장한다.
- 마지막에 최단거리를 저장한 배열에서 최댓값을 구해 그 값을 가진 원소의 개수 리턴.
<br>
시간복잡도는 BFS에서 O(n + m). n는 노드의 개수, m는 간선의 개수
공간복잡도도 인접리스트를 만드는 과정에서 O(n + m)
<br>
<br>
<br>
<br>
소요 시간: 35분
<br/>

[개별 - Minseon] 49189

---

programmers/17677/Yebin_17677.java

**[프로그래머스 17677번 뉴스 클러스터링](https://school.programmers.co.kr/learn/courses/30/lessons/17677)**
<br>
<br>
- 문자열 검색을 많이 해야 하므로 Hash 형태의 자료구조를 써야겠다. `HashMap`, `HashSet`
- J(a, b) 에서 a, b 모두 0이 되는 경우를 처리. 미리 두 집합이 비어있는 걸 확인해도 됨. 
<br>
<br>
- 구현
<br>
1. 두 문자열을 각각 다중집합(HashMap<원소, 개수>)으로 만듦
2. 두 다중집합에서 공통인 키를 뽑아 교집합 키로 만들고 개수를 셈 = a
3. 두 다중집합의 모든 키를 뽑아 합집합 키를 만들고 개수를 셈 = b
4. J(a, b) 계산 
<br>
- 시간복잡도 : 문자열 길이가 n이면 원소가 n-1 개. hash 의 검색시간은 1. 두 집합의 원소를 1:1 비교를 하진 않으므로 O(n) 
- 공간복잡도 : 두 다중집합을 저장하는 Map이 2개 * n-1, 교집합 최대 n-1, 합집합 최대 2n-2. 따라서 O(n)
<br>
<br>
<br>
<br>
1시간 
<br/>

[공통 - Yebin] 17677

---

programmers/155651/Yebin_155651.java

**[프로그래머스 155651번 호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)**
<br>
<br>
- 그리디하게 빈 방이 있으면 넣고 없으면 새 룸을 배정한다. 사실 방의 번호는 중요하지 않다. 
- 이전 대실의 종료 시간과 현재 대실의 시작 시간을 비교한다. 
- 항상 최대한 빨리 끝나는 방을 배정하면 되므로 우선순위큐를 사용하여 종료 시간을 저장한다.
- 시간 비교를 편하게 하려고 LocalTime을 사용해봤다. 
<br>
<br>
- 그리디
<br>
1. 예약을 시작 시간순으로 정렬
2. 제일 빨리 비는 방을 얻기 위해 우선순위큐 생성
3. 예약 배열을 순회하면서 방을 배정한다
- 방을 배정한다는 건 큐에 새로 추가하거나 빈 방을 큐에서 제거하고 새 손님을 받는 것이다
- 방을 새로 추가하게 되면 객실 수를 +1 한다 
<br>
- 시간복잡도 : Array.sort()가 O(nlogn), 배열을 순회하며 PriorityQueue에 삽입 삭제하는게 O(n * logn). 따라서 O(nlogn).
- 공간복잡도 : 큐는 최대 n=1000까지 찰 수 있으므로 O(n).
<br>
<br>
- LocalTime 써본다고 기억을 더듬어서 구현하다보니 시간이 걸림
- 청소가 끝나야 한다는 조건을 까먹었다가 10분 고민 
- 10분 고민하고 기억나서 청소 시간을 10분 더했는데 또 틀리다는거임!
- 생각해보니까 …

[공통 - Yebin] 155651

---

programmers/12941/Yebin_12941.java

**[프로그래머스 12941번](https://school.programmers.co.kr/learn/courses/30/lessons/12941)**
<br>
<br>
- 두 배열에서 숫자를 하나씩 뽑아 곱해서 최소의 누적합을 만든다.
- 곱해서 나오는 숫자가 최대한 작아야 한다. 
- 큰 숫자 * 큰 숫자 = 짱큰 숫자 가 나오기 때문에 A에선 가장 작은 숫자를, B에선 가장 큰 숫자를 뽑아서 곱한다.
- 매번 숫자를 빼고 제일 큰/작은 숫자를 갱신해야 하기 때문에 우선순위 큐를 사용하는 게 좋겠다. 
<br>
<br>
- 그리디
<br>
1. A,B 배열을 우선순위큐로 바꾼다. 단, A는 오름차순, B는 내림차순 큐이다.
2. 각 큐에서 수를 하나 씩 뽑아 곱하고 기존 누적합에 더하기를 배열 길이만큼 반복한다.
<br>
- 시간복잡도 : 큐로 만드는 데 O(n), 누적합을 만드는 데 O(n).
- 공간복잡도 : 큐 2개를 쓰니까 2n -> O(n).
<br>
<br>
❌ 
<br>
<br>
10분 
<br/>

[개별 - Yebin] 12941

---

programmers/87390/Yebin_87390.java

**[프로그래머스 87390번](https://school.programmers.co.kr/learn/courses/30/lessons/87390)**
<br>
<br>
- 칸에 들어가는 숫자는 좌표 중 큰 숫자 + 1 이라는 규칙이 있기 때문에 좌표를 계산해서 해당하는 칸의 숫자를 구하면 되겠다.
- left~right 간격이 최대 10^5 이니까 하나하나 계산해도 될 것이다.
<br>
<br>
- 구현
<br>
1. k번째 숫자에 대한 좌표를 구한다. 
- 행 = k / n; 
- 열 = k % n;
2. 칸의 숫자를 구한다. 
<br>
- 시간복잡도 : 계산을 right-left 만큼만 하면 됨. List를 int[] 로 바꾸는 시간은 모르겠으나 O(n) 정도 걸릴거라 생각.
- 공간복잡도 : right-left 길이의 List 가 필요. O(n)
<br>
<br>
처음에 좌표 등을 모두 int 로 했는데 tc12부터 다 실패했다. 
- 그래서 엣지케이스를 넣어봤더니 이상한 수가 나오더라. 
- right, left를 long으로 준 이유가 있었던거야. 
- 그래서 변수들을 다 long으로 바꾸니 통과.
<br>
<br>
30분 
<br/>

[개별 - Yebin] 87390

---

programmers/64065/Yebin_64065.java

**[프로그래머스 64065번 튜플](https://school.programmers.co.kr/learn/courses/30/lessons/64065)**
<br>
<br>
- 길이가 1이면 a1, 2면 a2까지, 이렇게 해서 길이가 n이면 a1 ~ an이 들어가므로 길이 n 집합과 이전 집합인 길이가 n-1인 집합은 딱 an만 차이 난다.
- 따라서 이전 집합과 다른 숫자 하나를 찾아서 튜플의 뒤쪽으로 추가하면 된다. 
<br>
<br>
- 구현
<br>
1. 문자열의 형식이 정해져 있으므로 양 끝의 {} 을 제거
2. 그리고 집합을 구분하는 },{으로 집합을 쪼갠다
3. 배열을 집합의 길이로 정렬한다 
4. 쪼갠 집합을 ,를 기준으로 원소를 분리하고
5. 튜플에 없는 숫자를 찾아 넣어준다 
<br>
- 시간복잡도 : split 하는 건 얼마나 걸리는지 모르겠으나 contains를 1~n 번 찾으므로 O(n^2)이다. 하지만 리턴하는 배열의 길이 즉 튜플의 길이가 500 이하인 경우만 입력받으니까 시간 초과는 없을 것.
- 공간복잡도 : 집합도 최대 500개 인데 길이가 1~500인,,, 그니까 O(n^2)?
<br>
<br>
- 처음에 split("},{") 이렇게 해서 집합을 분리하려는데 이런 오류가 떴다 
- 그니까 split이 정규식으로 패턴을 찾는다는 말이었다. 문제는 {와 } 라서 \\{ \\}으로 바꿔줬더니 오류 해결됨
- 그리고 처음에 },{으로 분리하고 0번과 n-1번 …

[개별 - Yebin] 64065

---

programmers/17684/Suhwa_17684.java

**[17684번](https://school.programmers.co.kr/learn/courses/30/lessons/17684)**
<br>
<br>
사전을 사용하는 구현문제, 관건은 얼마나 문자열 청크단위로 쪼개냐
c+w가 사전에 없으면 추가한다는거에서 제일 마지막원소를 뽑을일이 있을줄 알고 순서가 유지되는 linkedhashmap을 썼음
-> 근데 막상 풀다보니 어차피 value가 숫자라서 map의 사이즈로 마지막 value를 구할수가 있어서 그냥 map을 써도 되었을것같음.
단일 문자는 사전에 존재하고, 찾는 문자열이 사전에 존재하는지 찾는방법을 고민...
솔직히 복잡도 일단 포기하고 substring으로 일단 문자열 뒤부터 잘라서 하나씩 확인. 즉 KAKAO -없으면-> KAKA -> KAK -> KA -> K 이런순서.
테스트통과하는거보고 복잡도 계산하려했는데 다 통과해서 오잉 ㅎㅎ 이러는중~
<br>
<br>
map을 쓰는 구현 <- 사전에서 문자열을 찾는 과정이 중요
<br>
<br>
문자열의 문자1개당 시작문자~마지막문자의 반복  = n * (n-1)/2=> O(n^2)
<br>
<br>
좀더 효율적으로 사전에 존재하는 가능한 큰 문자열 청크를 찾고싶음
<br>
<br>
<br/>

[공통 - Suhwa] 17684

---

programmers/81302/Suhwa_81302.java

**[81302번](https://school.programmers.co.kr/learn/courses/30/lessons/81302)**
<br>
<br>
처음에는 탐색이라고 생각했는데, 어차피 각 P들의 조합이 맨해튼 거리 2초과임을 판단하는 문제라서 구현으로 생각.
(Pa, Pb) = (Pb, Pa) 각 맨해튼거리는 같기에 P들의 조합을 알아야함.
1. P들을 조합을 알기위헤 pPlaceList 함수로 각 P의 row,col을 저장
2. 해당 P들을 2중 for문을 통해 하나하나 맨해튼 거리 탐색(checkDistance)
2.1 맨해튼 거리가 2이하인경우 : 가운데 파티션이 있는지 탐색(checkPartition)
<br>
<br>
구현,완탐
<br>
P의 조합을 하나하나 검사
<br>
pPlaceList -> O(n^2) + checkDistance->O(n^2) => O(n^2)
<br>
<br>
처음에 ㅋㅋㅋ String[][]을 List<List<String>>으로 한번에 바꾸려고하다가...... stream을 중복되게 써서 classpath에러가 남. 에러메시지가 자세하지않아서 어디서 난에러인지 모르고 한참 디버깅함....
<br>
<br>
<br/>

[공통 - Suhwa] 81302

---

programmers/118666/Minseon_118666.java

**[프로그래머스 118666번](https://school.programmers.co.kr/learn/courses/30/lessons/118666)**
<br>
<br>
- 4가지 지표(R/T, C/F, J/M, A/N)에서 응답한 항목의 점수를 계산해서 검사 결과를 내는 문제.
- 매우 동의/비동의는 3점, 동의/비동의는 2점, 약간 동의/비동의는 1점, 모르겠음은 0점
- 문자열이 "RT"로 주어지면 매우 비동의 -> 매우 동의 순서로 점수가 할당된다.
- 선택지도 1이 매우 비동의 -> 7이 매우 동의
- 두 지표가 같은 점수일 경우 알파벳이 빠른 지표를 선택한다.
<br>
<br>
해시
<br>
- 해시를 이용해서 각 항목별 점수를 계산한다.
- 점수를 계산하는 메소드를 만들어서 4(모르겠음 - 0점)를 기준으로 그보다 작으면 첫번째 타입에, 크면 두번째 타입에 점수를 더한다.
- 점수 계산을 다 한 후에는 StringBuilder를 이용해서 조건에 맞게 검사 결과 문자열 생성
<br>
시간복잡도는 설문조사 개수에 비례하므로 O(n), 공간복잡도는 지표의 개수로 고정되어 있으므로 O(1)
<br>
<br>
<br>
<br>
소요 시간: 25분
<br/>

[개별 - Minseon] 118666

---

programmers/17684/Minseon_17684.java

**[프로그래머스 17684번](https://school.programmers.co.kr/learn/courses/30/lessons/17684)**
<br>
<br>
- 문자열에 대해 LZW 압축 결과 색인번호 배열을 구하는 문제.
1. A~Z까지 1~26으로 대입해서 사전을 초기화
2. 현재 입력과 일치하는 가장 긴 문자열 w 찾기
3. w에 해당하는 색인번호 출력
4. 처리하지 않은 다음 문자 c가 있으면 그 다음 인덱스에 w+c 등록
5. 2단계부터 반복해서 문자열 전체를 압축
<br>
<br>
해시
<br>
- 사전은 해시맵을 이용해서 구현한다. 이때, A~Z는 아스키 코드를 이용해서 반복문으로 넣어준다.
- StringBuilder를 이용해서 처리한 문자열은 delete 해준다. StringBuilder의 길이가 0이 되면 압축 결과를 리턴하는 알고리즘.
- LZW 압축 단계를 순서대로 구현해주면 된다. 사전에 존재하는 가장 긴 subString을 찾는 것이 관건인 문제.
- idx 변수를 이용해서 subString을 구한다. 현재 subString이 사전에 존재하면 subString에 그 다음 인덱스에 해당하는 문자를 추가하는 방식
<br>
- 해시 관련된 부분은 O(1)이므로 시간복잡도, 공간복잡도 모두 O(n).
<br>
<br>
처음에 처리된 문자열을 따로 구분하지 않고 인덱스로만 풀다보니 머리가 복잡해져서 StringBuilder로 바꿔서 풀었다. 근데 …

[공통 - Minseon] 17684

---

programmers/118668/Minseon_118668.java

**[프로그래머스 118668번](https://school.programmers.co.kr/learn/courses/30/lessons/118668)**
<br>
<br>
- 목표 알고력과 코딩력에 도달할 수 있는 최소 시간을 구하는 문제.
- 알고력과 코딩력을 올리는 방법은 다음과 같다.
1. 알고력과 코딩력은 각각 공부해서 1시간에 1씩 올릴 수 있다.
2. 현재 알고력과 코딩력으로 풀 수 있는 문제를 풀면 cost 시간동안 alp_rwd, cop_rwd만큼 올릴 수 있다.
- 같은 문제를 여러 번 풀 수 있고, 꼭 모든 문제를 다 풀 필요는 없다.
<br>
<br>
DP
<br>
- 문제를 순회하며 최대 알고력과 최대 코딩력을 구한다. 이때, 기존 알고력과 코딩력이 더 높은 경우가 있을 수 있으므로 초기값은 기존 알고력과 코딩력으로 세팅해준다.
- 주어지는 최대 알고력, 코딩력이 150이하이므로 151*151 크기의 2차원 dp 배열을 만든다. 이때 행이 알고력, 열이 코딩력이 되고 값은 시간이 된다.
- dp 배열은 Integer.MAX_VALUE로 초기화하고, dp[alp][cop] = 0으로 정의한다.
- alp ~ target_alp, cop ~ target_cop 만큼 순회하며 값을 업데이트한다.
1. 공부로 올리는 경우 : 알고력만 예로 들면, dp[i+1][j] = min(dp[i][j] + 1, dp[i+1][j])
2. 문제 풀이로 올리는 경우
- 현재 알고력과 코딩력으로 풀 수 없으면 continue
- 풀 수 …

[개별 - Minseon] 118668

---

programmers/81302/Minseon_81302.java

**[프로그래머스 81302번](https://school.programmers.co.kr/learn/courses/30/lessons/81302)**
<br>
<br>
- 5*5 크기의 5개의 대기실에서 각 대기실마다 모든 응시자가 거리두기를 지키고 있는지 구하는 문제.
- 각 응시자끼리 맨해튼 거리가 2보다 크거나, 응시자 사이에 파티션이 있으면 거리두기를 지키고 있는 것으로 판단.
<br>
<br>
완전탐색
<br>
(각 대기실 기준)
- 대기실에 있는 모든 응시자의 좌표를 구한다.
- 완탐으로 각 응시자끼리 거리두기를 지키고 있는지 판단한다. -> 거리두기를 지키지 않으면 바로 0 리턴.
- 맨해튼 거리가 2보다 크면 continue, 1이면 0 리턴(바로 옆 또는 앞뒤로 붙어있을 수밖에 없으므로)
- 맨해튼 거리가 2인 경우에는 파티션이 사이에 있는지 확인해야 한다.
- 일렬로 위치한 경우에는 사이 좌표에 파티션이 있는지 확인
- 대각선으로 위치한 경우에는 반대 방향 대각선 좌표에 파티션이 모두 있는지 확인
<br>
시간복잡도는 대기실 순회는 최대 O(25) = O(1)이므로 응시자 수 n에 대해 최악의 경우 O(n^2)
공간복잡도는 O(n)
<br>
<br>
<br>
<br>
소요 시간: 40분
<br/>

[공통 - Minseon] 81302

---

programmers/17684/Yebin_17684.java

**[프로그래머스 17684번 압축](https://school.programmers.co.kr/learn/courses/30/lessons/17684)**
<br>
<br>
- 문제에서 설명한 LZM 문자열 압축 알고리즘을 그대로 구현하면 되는 문제. 
<br>
<br>
- 구현
<br>
1. 사전을 초기화한다. 
2. start: w의 시작 위치, end: c+1의 위치로 하여 문자열을 자름
3. end를 오른쪽으로 옮겨가며 사전에서 검색되는 최대 길이의 w+c를 만듦
4. w인 [start, end-1)까지를 출력
5. w+c인 [start, end)까지를 사전에 등록 
6. 2~5를 start가 msg.length()-1 이 될 때까지 반복  
<br>
- 시간복잡도 : 사전에서 색인 번호 찾는거 O(n)
- 공간복잡도 : 사전 저장 외에 다른 공간을 쓰지 않으므로 O(n)
<br>
<br>
- substring(start, end)면  [start, end) 인거 순간 까먹어서 end 범위 조건을 잘못 줌.
- 문자열 처리에 substring을 쓰는것과 charAt과 StringBuffer를 쓰는 것 중 고민을 했는데 substring이 얼마나 느린지 몰라서 안되면 바꾸지는 생각으로 일단 substring을 씀. 테스트케이스에선 괜찮았지만 확실히 이유를 안다면 고민하는데 시간을 덜 썼을 것. 
<br>
<br>
46분
<br/>

[공통 - Yebin] 17684

---

programmers/87946/Yebin_87946.java

**[프로그래머스 87946번 피로도](https://school.programmers.co.kr/learn/courses/30/lessons/87946)**
<br>
<br>
- 경로는 필요 없고 최대 던전 개수만 세면 된다
- 예제를 보면 꼭 최소hp가 크고 소요hp가 작은 걸 먼저 들어간다고 해서 최적의 해라는 보장이 없다 => 그리디 아님
- 순열 만들기를 응용해서 모든 경우의 수에 따라 방문 던전 수를 세면 될 것 같다
- 단 최소hp 조건을 만족해야 한다
- 최소hp와 소요hp 조건이 잘못된 경우를 검사하진 않아도 된다
<br>
<br>
- 완전탐색
<br>
1. 순열 만드는 방식을 응용해서 던전 방문 경우의 수를 구할 수 있는 코드를 작성
2. 최소hp 조건에 부합하지 않는 경우는 탐색하지 않도록 처리
3. 재귀 단계를 들어갈 때마다 현재 카운트를 저장하여 방문한 던전 수를 리턴한다 
<br>
- 시간복잡도 : 모든 경우의 수를 세어서 O(n!)이지만 8! 정도면 4xxxx 대여서 괜찮다. 
- 공간복잡도 : 재귀를 쓰고 최대 8까지 쌓으므로 스택 메모리에 O(n).
<br>
<br>
- 테스트케이스 설명을 충분히 읽지 않고 던전 정렬부터 하려고 한 점
- 정렬 결과 보고 아차 싶어서 설명을 다시 제대로 읽긴 함
- 설명에 친절히 정렬이 아니라 완탐을 하라는 뉘앙스를 줌에도 그 힌트를 받아먹지 못하는 건 실전에서 문제가 된다ㅠ
<br>
<br>
30분
<br/>

[개별 - Yebin] 87946

---

programmers/81302/Yebin_81302.java

**[프로그래머스 81302번 거리두기 확인하기](https://school.programmers.co.kr/learn/courses/30/lessons/81302)**
<br>
<br>
- 어떤 사람의 맨해튼 거리 2 이내에 다른 사람이 있으면 안됨
- 사람이 있을 때 마다 거리를 체크하고 거리두기를 지키지 않은 경우 바로 탐색을 종료하자
- 거리 체크를 얼마나 반복을 덜하고 체크하는지가 실행 시간을 결정할 거 같다 
<br>
<br>
- 완전탐색
- 구현 
<br>
1. 응시자가 보이는 대로 맨해튼거리2 안에 있는지 확인 
2. 거리두기 미준수 발견 시 바로 그 대기실 탐색 멈춤 
2.1 거리가 1 (상하좌우)
2.2 거리가 2 (대각선, 상하좌우+2)
2.2.1 단 사이에 벽이 있는 경우 괜찮음
<br>
- 시간복잡도 : 대기실의 개수는 항상 5, 대기실의 크기는 항상 5*5 이다. 최악의 경우가 다섯번째 대기실이라고 생각하는데 그 경우에도 13명의 응시자에 대해서만 탐색하면 된다. 따라서 n = 5 * 13 = 65 번 계산한다. 따라서 O(1).
- 공간복잡도 : 좌표이동을 위한 변화량 저장 배열과 주변 탐색 시에 쓰는 지역 변수들 뿐이므로 O(1).
<br>
<br>
- places 배열을 조작해야 하는게 아닌데 처음에 굳이 char[][]로 만들려고 했던 점 
- 처음에 벽 체크를 까먹고 구현한 점 
- 결국 급하게 문제를 풀려던게 문제다
<br>
<br>
48분
<br/>

[공통 - Yebin] 81302

---

programmers/42586/Yebin_42586.java

**[프로그래머스 42586번 기능개발](https://school.programmers.co.kr/learn/courses/30/lessons/42586)**
<br>
<br>
- 배포 순서 있음
- 작업 개수 100개 이하 
- 배포 하루 한 번
<br>
<br>
- 구현
- 큐 
<br>
1. 모든 작업이 100이 되는데 걸리는 일수를 센다
2. 날자 개수를 세서 리턴
<br>
- 시간복잡도 : 작업 완료 날짜 세는데 O(n), 작업 배포 시기 결정하는데 O(n) 이므로 최종 O(n).
- 공간복잡도 : 작업 완료 날짜를 저장하는 배열 O(n)
<br>
<br>
<br>
<br>
15분
| 큐 ❌ | 큐 ⭕ , List에 LinkedList 사용 | 큐 ⭕ , List에 ArrayList 사용 |
|--|--|--|
|<img width="428" alt="스크린샷 2023-11-24 오후 11 36 40" src="https://github.com/Algorithm-SQL-Study/Algorithm-SQL-Study/assets/69137469/6345f6c9-156f-4e3b-b694-a4c805102ce3">|<img width="385" alt="스크린샷 2023-11-25 오전 12 07 26" src="https://github.com/Algorithm-SQL-Study/Algorithm-SQL-Study/assets/69137469/2f6f87 …

[개별 - Yebin] 42586

---

programmers/60058/Minseon_60058.java

**[프로그래머스 60058번](https://school.programmers.co.kr/learn/courses/30/lessons/60058)**
<br>
<br>
균형잡힌 괄호 문자열을 올바른 괄호 문자열로 변환하는 문제. 변환 과정은 다음 단계를 따른다.
```
1. 입력이 빈 문자열인 경우, 빈 문자열을 반환합니다. 
2. 문자열 w를 두 "균형잡힌 괄호 문자열" u, v로 분리합니다. 단, u는 "균형잡힌 괄호 문자열"로 더 이상 분리할 수 없어야 하며, v는 빈 문자열이 될 수 있습니다. 
3. 문자열 u가 "올바른 괄호 문자열" 이라면 문자열 v에 대해 1단계부터 다시 수행합니다. 
3-1. 수행한 결과 문자열을 u에 이어 붙인 후 반환합니다. 
4. 문자열 u가 "올바른 괄호 문자열"이 아니라면 아래 과정을 수행합니다. 
4-1. 빈 문자열에 첫 번째 문자로 '('를 붙입니다. 
4-2. 문자열 v에 대해 1단계부터 재귀적으로 수행한 결과 문자열을 이어 붙입니다. 
4-3. ')'를 다시 붙입니다. 
4-4. u의 첫 번째와 마지막 문자를 제거하고, 나머지 문자열의 괄호 방향을 뒤집어서 뒤에 붙입니다. 
4-5. 생성된 문자열을 반환합니다.
```
<br>
<br>
재귀
<br>
- 다음과 같이 재귀함수를 구성한다.
- 현재 문자열(w)이 올바른 괄호 문자열이면 w 리턴
- w를 균형잡힌 괄호 문자열 u, v로 분리
- u가 올바른 괄호 문자열이면 빈 문자열에 u를 붙이고 v에 대해 재귀함수를 호출한다.
- u가 올바른 …

[개별 - Minseon] 60058

---

programmers/92341/Minseon_92341.java

**[프로그래머스 92341번](https://school.programmers.co.kr/learn/courses/30/lessons/92341)**
<br>
<br>
- 입출차 내역을 보고 누적 주차 시간을 구해 주차 요금을 정산하는 문제.
- 입차 내역만 있고 출차 내역이 없으면 23:59에 출차했다고 가정한다.
- 주차 요금은 기본 요금 + 초과 요금. 이때, 기본 시간보다 적게 주차했어도 기본 요금을 받는다.
- 차량 번호 순서대로 배열에 담아서 리턴.
<br>
<br>
해시, 구현
<br>
- 차량 번호를 key, 누적 주차 시간을 value로 하는 해시맵을 이용한다.
- 기본 시간과 단위 시간은 분 단위이므로 시간을 HH:MM 에서 HH*60 + MM 분으로 바꿔준다.
- 차량 번호, 입출차 시각을 기준으로 정렬해서 같은 차량 번호에 대해 입차, 출차 기록을 짝 지어준다.
- 맨 마지막에 입차 기록만 남는 경우 출차 시각을 23:59로 놓는다.
<br>
시간복잡도: 기록의 개수를 N이라 하면 정렬하는 데 O(NlogN), 반복문은 모두 O(N)이므로 O(NlogN)
공간복잡도: 차의 개수를 m이라 하면 O(m)
<br>
<br>
누적 시간은 맞는데 요금이 자꾸 틀려서 뭐지 했는데 기본 요금을 한 번만 더해야 되는데 계속 기본요금 * 전체시간/기본시간을 하고 있었음.. 바본가...?
<br>
<br>
소요 시간 : 1시간
<br/>

[공통 - Minseon] 92341

---

programmers/43236/Minseon_43236.java

**[프로그래머스 43236번](https://school.programmers.co.kr/learn/courses/30/lessons/43236)**
<br>
<br>
- 징검다리에서 출발점에서 도착점 사이에 바위가 놓여 있는데, 바위를 n개 제거한 뒤 각 지점 사이의 거리의 최솟값 중에 가장 큰 값을 구하는 문제.
- distance의 최댓값이 1,000,000,000이고 바위 개수의 최댓값은 50,000이므로 완탐으로는 풀 수 없다. -> 이분 탐색
<br>
<br>
이분 탐색
<br>
- mid값을 바위 사이의 간격의 최솟값으로 정의한다.
- 바위들의 간격을 계산하면서 mid보다 작으면 간격에 최솟값보다 작은 것이 되어버리므로 해당 바위를 제거한다.
- 그렇게 제거한 바위의 개수가 n보다 크면 간격을 줄이고, n보다 작으면 간격을 늘린다.
<br>
O(NlogN)
<br>
<br>
주어진 테스트케이스와 반례에서는 마지막 바위를 제거하는 경우가 없어서 그 경우를 놓쳤다.
<br>
<br>
소요 시간 : 1시간 12분
<br/>

[개별 - Minseon] 43236

---

programmers/154538/Minseon_154538.java

**[프로그래머스 154538번](https://school.programmers.co.kr/learn/courses/30/lessons/154538)**
<br>
<br>
x에서 +n, *2, *3 세가지 방법을 이용해 y로 도달하는 최소 횟수를 구하는 문제
<br>
<br>
DP, BFS 두 가지 방법으로 풀이
<br>
[DP] : x -> y
- dp 배열에 연산 횟수 저장
- i+n <= y, i*2 <= y, i*3 <= y 면 dp 값 업데이트
[BFS] : y -> x
- Count 클래스를 만들어서 현재 값과 연산 횟수 저장
- i > x이면 i-n queue에 추가, i가 2나 3으로 나누어 떨어지는지 확인하고 queue에 추가
<br>
dp: O(y-x)
bfs: x -> y보다 y -> x로 가는 것이 시간적으로 더 유리했음.
<br>
<br>
<br>
<br>
소요 시간 : 15분, 10분
|DP|BFS|
|---|---|
|<img width="675" alt="11/30 프로그래머스 154538(dp-1)" src="https://github.com/Algorithm-SQL-Study/Algorithm-SQL-Study/assets/76639061/c6caa767-910c-414d-82b3-4004f419fb96"><img width="674" alt="11/30 프로그래머스 154538(dp-2)" …

[공통 - Minseon] 154538

---

baekjoon/2447/Minseon_2447.java

**[백준 2447번](https://www.acmicpc.net/problem/2447)**
<br>
<br>
- N은 3의 거듭제곱, 별을 찍는 부분의 크기는 N*N
- 주어진 패턴에 맞게 별을 찍는 문제.
- N = 3일 때, 가운데에 공백이 있고, 가운데를 제외한 모든 칸에 별이 하나씩 있는 패턴이다.
```
***
* *
***
```
- N > 3일때, 크기 N의 패턴은 공백으로 채워진 가운데의 (N/3)×(N/3) 정사각형을 크기 N/3의 패턴으로 둘러싼 형태이다.
N = 9일 때,
```
*********
* ** ** *
*********
***   ***
* *   * *
***   ***
*********
* ** ** *
*********
```
<br>
<br>
재귀
<br>
- N = 9일 때를 봤을 때, 공백인 부분(작은 공백)은 a[1][1], a[1][4], a[1][7], a[4][1], a[7][1], a[4][7], a[7][4], a[7][7]로 i % 3 == 1 && j % 3 == 1일 때이다.
- 큰 공백은 N이 9일 때, a[3][3] ~ a[5][5]이고 N이 27일 때는 a[9][9] ~ a[17][17]로 (i / N) % 3 == 1, (j / N) % 3 == 1일 때이다.
- 즉, (i / N) % 3 == 1 && (j / N) % 3 == 1이면 stars[i][j]는 공백이다.
<br>
O(n^2)
<br>
<br>
처음에 그냥 …

[개별 - Minseon] 2447

---

programmers/92341/Suhwa_92341.java

**[92341번](https://school.programmers.co.kr/learn/courses/30/lessons/92341)**
<br>
<br>
입차-출차기록으로 시간계산 -> 자바 시간클래스로
주차요금 계산 -> 올림
결과출력시 -> 숫자대로 오름차순
<br>
<br>
구현
<br>
문제가 써진 그대로
1. 입차-출차를 짝지어서 시간(분)을 계산
2. 입차기록만 남아있는 기록은 자동 23:59 출차로 주차시간 계산
3. 1,2,에서 계산한 주차시간으로 주차비 계산
4. 3을 자동차번호 오름차순으로 정렬해 출력
<br>
어차피 record를 탐색해야함 -> O(n)
<br>
<br>
일단... 자잘한 고려사항이 있어서 귀찮았음. 구현은 쉽고 노가다에 가까운 문제인듯
<br>
<br>
<br/>

[공통 - Suhwa] 92341

---

programmers/154538/Suhwa_154538.java

**[154538번](https://school.programmers.co.kr/learn/courses/30/lessons/154538)**
<br>
<br>
최소단계 -> BFS
주의할점 x가 주어진 연산으로 y에 접근하지 못할경우 분기처리 주의 : 주어진 연산 3개가 +, * 이며 x,y,n은 자연수임으로 주어진 연산으로는 값이 늘어나기만함 -> 즉 현재 값에 주어진 연산을 처리한새로운 값이 y 보다 크면 y가 될수있는 확률이 사라짐.
성능 -> visited 배열로 방문한값은 더이상 방문못하게처리
<br>
<br>
bfs
<br>
bfs
<br>
방문처리를 맵으로 할지 배열로 할지 고민했으나 y가 1000000 이하이기때문에 배열로 처리
<br>
<br>
<br>
<br>
23분 소요
<br/>

[공통 - Suhwa] 154538

---

programmers/68645/Minseon_68645.js

**[프로그래머스 68645번](https://school.programmers.co.kr/learn/courses/30/lessons/68645)**
<br>
<br>
한 변의 길이가 n인 정삼각형 모양의 배열을 아래와 같이 달팽이 채우기로 숫자를 채우는 문제.
<br>
<br>
구현
<br>
처음에는 수학적인 규칙이 있을까해서 규칙을 찾아봤는데 너무 복잡해서 단순하게 채우기로 했다.
1. 먼저 삼각형 왼쪽 변을 채운다. [0][0] ~ [n-1][0]
2. 삼각형 밑변을 채운다. [n-1][1] ~ [n-1][n-1]
3. 삼각형 오른쪽 변을 채운다. [n-2][n-2] ~ [1][1]
- 그 다음 삼각형 시작점으로 이동해서 앞의 과정을 반복한다. [2][1] ~
<br>
O(n^2)
<br>
<br>
요즘 하고 있는 개인 플젝에서 js를 쓰고 있어서 연습할 겸 일주일에 1~2 문제는 js로 풀어보려고 함.
<br>
<br>
소요 시간 : 48분
<br/>

[개별 - Minseon] 68645

---

programmers/42627/Minseon_42627.java

**[프로그래머스 42627번](https://school.programmers.co.kr/learn/courses/30/lessons/42627)**
<br>
<br>
- 작업 요청 시간과 소요 시간이 주어지면 각 작업의 요청 시간부터 수행 완료하는 데까지 걸리는 시간의 평균의 최솟값을 구하는 문제.
- 하드디스크는 한 번에 하나의 요청만 수행 가능
[A->B->C]
[A->C->B]
<br>
<br>
우선순위큐
<br>
- 우선순위큐 2개를 사용한다. 첫번째 우선순위큐는 요청시간순으로 정렬하고, 두번째 우선순위큐는 현재 시점에서 수행할 수 있는 작업 중 소요시간순으로 정렬한다.
- 주어진 작업을 모두 첫번째 우선순위큐에 넣는다.
- 각 작업의 소요 시간은 대기 시간 + 수행 시간
- 이때, 대기 시간은 현재 시점 - 요청 시점이다.
- 요청 시점이 현재 시점 뒤인 경우에는 요청 시점 + 수행 시간이 현재 시점이 되고, 대기 시간은 0이 된다.
- 현 시점에서 수행가능한 작업을 모두 수행했으나 남은 작업이 있는 경우 현재 시점을 남은 작업 중 가장 빠른 요청 시간으로 한다.
- 현 시점에서 수행가능한 작업을 두번째 우선순위큐에 모두 넣고 과정을 반복한다.
<br>
O(NlogN)
<br>
<br>
<br>
<br>
소요 시간 : 1시간
<br/>

[개별 - Minseon] 42627

---

programmers/134239/Minseon_134239.java

**[프로그래머스 134239번](https://school.programmers.co.kr/learn/courses/30/lessons/134239)**
<br>
<br>
```
1-1. 입력된 수가 짝수라면 2로 나눕니다.
1-2. 입력된 수가 홀수라면 3을 곱하고 1을 더합니다.
2.결과로 나온 수가 1보다 크다면 1번 작업을 반복합니다.
```
초항 k에 대해 위 방법대로 우박수열을 구하고, 주어진 범위만큼 우박수열로 만든 꺾은선 그래프를 정적분하는 문제.
<br>
<br>
구현, 수학
<br>
- 우박수열 구하기
- k > 1일 때까지 짝수면 /2, 홀수면 *3+1을 해서 우박수열을 구한다. 이 과정에서 n++을 해서 1이 될 때까지의 횟수를 구한다.
- 우박수열 리스트의 인덱스가 꺾은선 그래프의 x좌표, 값이 y좌표가 된다.
- 정적분
- 범위 [a, b]에서 b가 0보다 작으면 b = n + b를 한다. ex) b == -1이면, b = n - 1
- a > b이면 유효하지 않은 범위로 간주되어 정적분 결과는 -1.0이 된다.
- for문을 이용해서 꺾은선 그래프와 x=a, x=b, y=0으로 이루어진 영역의 넓이를 x~x+1 단위로 나눠서 구한다.
- 이때, 넓이는 사다리꼴의 넓이 방정식을 이용한다.
<br>
O(n)
<br>
<br>
정답률이 낮은 문제라 반례 찾는 연습할 수 있을 거 같아서 풀었는데 음... 그대로 구현하니까 통과해서 읭? 했다. 문제 고르기 너무 어려운 …

[개별 - Minseon] 134239

---

programmers/92341/Yebin_92341.java

**[프로그래머스 92341번 주차 요금 계산](https://school.programmers.co.kr/learn/courses/30/lessons/92341)**
<br>
<br>
- 차 번호로 검색해야하므로 HashMap을 써야겠다.
- 올바르지 않은 입력은 없으므로 그에 대한 처리가 필요 없다.
- 출차가 안된 차를 23:59에 출차된 것으로 나머지 처리를 해줘야 한다.
- 분단위로 계산하므로 시간을 분으로 표현하는게 좋겠다.
<br>
<br>
- 구현
- 해시
<br>
- 주차 기록 정리
- 입차내역이면 주차장에 차량번호와 입차시간을 저장한다.
- 출차기록이면 주차장에서 입차시간을 지우고 주차시간을 계산해서 누적주차시간 맵에 저장한다.
- 주차장에 남은 차가 있으면 출차시간을 23:59로 설정해서 누적주차시간에 저장한다.
- 주차 요금 계산
- 누적주차시간의 키를 오름차순으로 정렬한다.
- 오름차순 키로 누적주차시간을 꺼내서 주차 요금을 계산한다. 
- 결과 반환 
- List 를 Array로 만들기 위해 stream 활용
<br>
- 시간복잡도 : records가 n개라면 주차 대수가 최대 n이므로 O(n)
- 공간복잡도 : 차량이 최대 n개이므로 O(n)
<br>
<br>
- 어려운 알고리즘은 전혀 없고 구현만 하면 되는 문젠데 손이 느린건지 머리가 느린건지 오늘따라 구현이 느렸다.
<br>
<br>
49분
<br/>

[공통 - Yebin] 92341

---

programmers/154538/Yebin_154538.java

**[프로그래머스 154538번 숫자 변환하기](https://school.programmers.co.kr/learn/courses/30/lessons/154538)**
<br>
<br>
- ~처음엔 그리디/DP/BFS 로 푸는 방식이 생각남~
- ~10^6이라 그리디가 더 맞지 않을까 해서 그리디로 풀어봤으나 tc 반절은 실패함~
- ~그리디로 풀 수 없는 경우가 있겠거니 하고 DP로 바꿨다~
- DP로 도달할 수 있는 칸에 최대한 적은 횟수로 가는 방법을 배열에 저장함
- 배열을 -1로 초기화하고 -1인 칸은 도달하는 방법이 없는 것으로 생각한다
<br>
<br>
- DP
<br>
- 배열 초기화
- y 크기의 배열을 생성
- -1로 초기화
- DP
- x에서 시작
- +n, *2, *3을 해서 갈 수 있는 칸을 판단
- 그 칸이 -1이면 아직 도달한 적 없는 칸임. [i]에서의 방법의 수에 +1 하여 저장.
- 그 칸이 -1이 아니면 그 칸에 저장되어 있는 방법의 수와 [i]에서의 방법의 수를 비교하여 작은 것을 저장.
- 결과 반환
- 만약 [y]에 도달할 수 없다면 -1으로 남아있을 것이므로 그대로 [y] 반환
<br>
- 시간복잡도 : 10^8이 대충 1초 걸린다니까 O(y)이고 10^6이면 대충 1 ^ -2 초 ? 
- 공간복잡도 : y까지 전부 저장해야 하므로 O(y)
<br>
<br>
- 그리디는 왜 안될까
<br>
<br>
30분
<br/>

[공통 - Yebin] 154538

---

programmers/42587/Yebin_42587.java

**[프로그래머스 42587번 프로세스](https://school.programmers.co.kr/learn/courses/30/lessons/42587)**
<br>
<br>
- 우선순위가 더 높은 프로세스가 존재한다는 걸 어떻게 알까 생각해봤다.
- 우선순위의 범위는 [1,9]로 정해져 있다. 
- 우선순위마다 프로세스 개수를 세서 저장하고 해당 우선순위의 프로세스를 실행할 때마다 갱신해주면 될 것 같다.
- 프로세스가 최대 100개니까 표적 프로세스의 우선순위가 딸려도 n번쯤 우선순위를 세볼것이다. 
<br>
<br>
- 큐
<br>
- 우선순위 배열 만들기
- 프로세스를 큐에 넣으면서 우선순위 배열에 개수를 갱신한다.
- 큐에서 프로세스 탐색
- 큐에서 프로세스를 꺼냄
- 우선순위를 알아본다
- 현재 프로세스의 우선순위보다 더 중요한 프로세스가 있는지 개수로 확인한다 (0이 아닐 것)
- 더 중요한 게 있으면 프로세스를 다시 큐에 넣는다
- 아니면 실행순서++하고 우선순위 배열을 갱신한다
- 표적 프로세스면 실행을 중단한다
- 결과 반환
- 현재 실행순서를 반환
<br>
- 시간복잡도: 표적이 맨 뒤에 있고 우선순서가 가장 낮아도 n번째에는 실행하게 됨. O(n);
- 공간복잡도: 우선순위 배열 O(1), 실행 대기 큐 O(n); 따라서 O(n);
<br>
<br>
❌ 
<br>
<br>
15분
<br/>

[개별 - Yebin] 42587

---

programmers/131127/Yebin_131127.java

**[프로그래머스 131127번 할인 행사](https://school.programmers.co.kr/learn/courses/30/lessons/131127)**
<br>
<br>
- 매번 열흘의 구간에서 숫자를 세고 있으면 오래걸릴거다
- 슬라이딩 윈도우 처럼 열흘을 구간으로 정하고 세일 품목이 맞는지를 확인한 뒤 앞을 버리고 뒤를 더하자
- 품목이 모두 소문자라서 따로 처리는 필요 없고 검색을 위해 HashMap 사
<br>
<br>
- 해시
- 굳이 따지자면 슬라이딩 윈도우?
<br>
- 초기 열흘치 세일 품목 세기
- 처음 열흘치 세일 품목을 세서 HashMap으로 저장
- 구간을 옮겨가며 세일 품목 체크하고 회원 등록 일수 세기
- 회원 등록 가능한 날인지 확인
- 앞을 버리고 구간을 이동하여 뒤를 채움
- 만약 구간을 이동하다가 맨 뒤가 구간의 끝을 넘어가면 탐색을 끝내야함
- 결과 반환
- 총 등록 일수를 반환
<br>
- 시간복잡도: 초기데이터 세팅 O(1), 슬라이딩 윈도우로 구간 탐색 O(n-10); 따라서 O(n);
- 공간복잡도: 품목을 맵에 저장하는데 최대 10개니까 O(1); 
<br>
<br>
- 생각보다 실행시간이 오래 걸린다? 다른 풀이를 찾아봐야겠음.
<br>
<br>
30분 
<br/>

[개별 - Yebin] 131127

---

programmers/49993/Yebin_49993.java

**[프로그래머스 49993번 스킬트리](https://school.programmers.co.kr/learn/courses/30/lessons/49993)**
<br>
<br>
- 선행 스킬을 먼저 배우지 않았다는 걸 어떻게 확인할 수 있을까?
- 문자열에서 스킬을 뽑아 이 스킬이 순서에 있는 것인지 확인하고, 순서에 있다면 선행 스킬을 통과 했는지를 확인해야 한다. 
- 순서에 있는지 검색하기 위해 HashMap<스킬 문자, 순서> 형태로 저장하면 좋겠다.
<br>
<br>
- 완전탐색
- 해시
<br>
- 스킬 순서 맵에 저장
- 스킬트리마다 선행 조건을 갖췄는지 확인
- 스킬 순서는 무조건 맨 앞에서부터 충족해야 하므로 인덱스 0에서 시작
- 순서에서 현재 통과해야 하는 스킬을 인덱스로 가리키고 있다가 현재 인덱스보다 후의 스킬을 배우려고 하면 불가능한 스킬트리로 판단
- 결과 반환 
<br>
- 시간복잡도 : 모든 스킬을 다 확인하므로 O(n);
- 공간복잡도 : 스킬 순서 맵 외에 추가적으로 요하는 공간이 없음. O(m), m은 선행 스킬 순서의 길이.
<br>
<br>
❌ 
<br>
<br>
15분 
<br/>

[개별 - Yebin] 49993

---

programmers/150368/Yebin_150368.java

**[프로그래머스 150368번 이모티콘 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/150368)**
<br>
<br>
- 각 사용자들이 원하는 할인율기준, 할인금액기준이 다르다. 일관적인 기준이 없으므로 모든 경우를 다 해봐야 한다. 
- 할인율은 4가지 경우가 있으므로 최대 4^7 가지 경우에 대해 임티플러스 가입자와 임티구매금액을 구해보면 된다
- 중복순열을 만드는 것과 같은데 따로 라이브러리가 없는걸로 알아서 재귀적으로 구현
<br>
<br>
- 완전탐색
- 재귀
<br>
- 할인율 중복순열 구하기 
- 재귀적으로 각 자리에 10~40 할인율을 넣어서 배열을 채운다 
- 배열을 다 채우면 임티플러스수와 임티구매금액을 구한다
- 각 경우에 대해 임티플러스수와 임티구매금액을 구하기 
- 임티플러스수와 임티구매금액을 지역변수로 하면 중복순열 구하는 메서드에서 할게 너무 많아서 멤버필드로 선언
- 각 사용자마다 임티플러스를 구매할지 임티를 구매할지 정한다
- 결과 반환
- 임티플러스수와 임티구매금액을 배열에 담아서 반환
<br>
이모티콘수가 n, 사용자수가 m일 때
- 시간복잡도 : 중복순열을 구하는 재귀 함수가 O(n), 이모티콘구매결과 구하는 함수가 O(n * m);
- 공간복잡도 : 스택메모리에서 재귀가 n만큼 쌓일테니 O(n). 따로 사용하는 자료구조는 없다;
<br>
<br>
- 할인율을 반영해서 구매금액을 …

[공통 - Yebin] 150368

---

programmers/76502/Yebin_76502.java

**[프로그래머스 76502번 괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)**
<br>
<br>
- 괄호 짝맞추기는 전통적인 스택 활용 문제
- 근데 이제 회전을 곁들인!
- 모든 경우를 다 탐색해야 한다
- 회전을 LInkedList를 이용해서 물리적으로 할까 고민했으나 문자열이 달라지는건 아니므로 인덱스를 활용해서 논리적으로 회전시키기로함
- 시작점을 옮기면 회전한 효과가 난다
- 인덱스 범위를 넘어가면 앞으로 돌아가도록 한다 (i - n)
<br>
<br>
- 완전탐색 
- 스택
<br>
- 문자열 회전
- 인덱스를 이동하여 논리적으로 회전시킴
- 괄호 짝 맞추기
- 열린 괄호면 스택에 넣고 
- 닫힌 괄호면 다음을 확인
- 스택의 맨 위가 같은 종류(소|중|대)의 열린 괄호라면 올바름
- 결과 반환
<br>
- 시간복잡도 : 길이가 n인 문자열에 대해 n번 회전하니 O(n^2). n이 최대 1000이므로 10^6 번 정도는 완탐 할만하다고 생각
- 공간복잡도 : 회전할때마다 최대 길이 n인 스택이 만들어지니 O(n).
<br>
<br>
<br>
<br>
20분 
<br/>

[개별 - Yebin] 76502

---

programmers/12924/Yebin_12924.java

**[프로그래머스 12924번 숫자의 표현](https://school.programmers.co.kr/learn/courses/30/lessons/12924)**
<br>
<br>
- 최종 숫자로부터 경우의 수를 세기는 어렵다.
- DP의 memoizaion 방식을 활용하자.
- 연속된 숫자를 더해서 나오는 수마다 경우의 수를 +1 해주자.
<br>
<br>
- DP
<br>
- 연속된 숫자 더하기
- 숫자 한 개도 연속된 숫자로 치므로 메모 배열을 1로 초기화
- 1~n-1 각각의 경우에 대해 연속된 숫자를 계속 더해서 메모 배열에 +1 한다
- 결과 반환
- 메모 배열에서 숫자 n 위치의 결과를 반환
<br>
- 시간복잡도 : n(n+1)/2 라서 O(n^2)이긴 하지만 10^8이면 1초를 넘진 않을 것
- 공간복잡도 : 메모 배열이 O(n)
<br>
<br>
❌ 
<br>
<br>
10분 
<br/>

[개별 - Yebin] 12924

---

programmers/92342/Yebin_92342.java

**[프로그래머스 92342번 양궁대회](https://school.programmers.co.kr/learn/courses/30/lessons/92342)**
<br>
<br>
- ~처음엔 화살개수만큼 중복조합을 해서 완전탐색 하는 방법을 생각했음~ 
- ~하지만 11^n은 시간이 부족할 것 같아 다른 방법을 생각해보기로 함~
- 라이언이 점수를 가져갈 칸을 선택하는 모든 경우를 탐색해보기로함
- 재귀 함수로 각 칸의 점수를 가져가는 경우/못 가져가는 경우를 모두 고려
<br>
<br>
- 완전탐색
- 빡구현
<br>
- 모든 경우 만들기
- 라이언이 각 칸의 점수를 가져갈 경우/안 가져갈 경우를 모두 고려한다
- 재귀 함수로 구현 
- 라이언의 화살로 가능한 경우가 맞는지 확인
- 라이언이 이길 판으로 정해진 곳은 어피치보다 1개 더 많은 화살을 쏜 것으로 저장
- 왜냐하면 낮은 점수에 더 많이 써야 하므로
- 중도에 화살이 부족하면 불가능한 경우로 판단
- 남은 화살은 0점에 쏜 것으로 저장
- 라이언이 이기는 경우가 맞는지 확인
- 라이언점수가 어피치점수보다 커야 함
- 최대 점수차 갱신
- 점수차 구하기
- 점수차가 저장된 최대 점수차와 같으면 가장 낮은 점수를 더 많이 맞힌 경우를 저장
- 결과 반환
- 최대 점수차가 0 초과가 아니면 라이언이 진 것 
<br>
- 시간복잡도 : 2^10 = 2048 번만 계산해보면 됨. 각 경우는 O(n).
- 공간복잡도 : 스택 메모리를 …

[공통 - Yebin] 92342

---

programmers/42579/Minseon_42579.java

**[프로그래머스 42579번](https://school.programmers.co.kr/learn/courses/30/lessons/42579)**
<br>
<br>
- 장르별로 가장 많이 재생된 두 곡을 뽑아 베스트앨범을 만드는 문제.
- 장르는 전체 재생 횟수가 많은 순으로 정렬.
- 장르 내에서는 재생 횟수 내림차순 > 고유번호 오름차순으로 정렬.
- 장르에 한 곡 밖에 없으면 한 곡만 포함.
<br>
<br>
해시
<br>
- (장르, 해당 장르의 전체 재생 횟수)로 이루어진 해시맵과 (고유번호, 장르)로 이루어진 해시맵을 이용한다.
- 주어진 전체 노래를 순회하며 두 해시맵을 업데이트한다.
- (장르, 해당 장르의 전체 재생 횟수)를 재생 횟수 기준 내림차순으로 정렬한다.
- 정렬한 장르 배열을 순회하며 베스트 앨범에 들어갈 수록곡을 정한다.
- 가장 많이 재생한 곡을 first, 두번째로 많이 재생한 곡을 second라 하면, first부터 비교 후 second와 비교.
- 한 곡 밖에 없을 경우에는 한 곡만 수록.
<br>
시간복잡도: 해시맵 정렬하는 데 O(NlogN), 베스트 앨범을 만드는 데 O(NM) -> 최종 O(NM)
공간복잡도: O(N + M)
<br>
<br>
<br>
<br>
소요 시간 : 53분
<br/>

[개별 - Minseon] 42579

---

programmers/60061/Minseon_60061.java

**[프로그래머스 60061번](https://school.programmers.co.kr/learn/courses/30/lessons/60061)**
<br>
<br>
기둥과 보의 설치 조건에 의거해서 작업 순서대로 설치 또는 삭제한 결과를 리턴하는 문제.
- 작업은 [시작 좌표, 기둥/보, 설치/삭제]로 주어진다.
- 기둥은 바닥에 설치하거나 보의 한쪽 끝 위에 설치하거나 다른 기둥 위에 설치할 수 있다.
- 보는 한쪽 끝이 기둥 위에 있거나 양쪽 끝이 다른 보와 연결되어 있어야 한다.
- 기둥이 차지하는 영역은 (x, y), (x, y+1). 보가 차지하는 영역은 (x, y), (x+1, y)
- 삭제했을 때 남아있는 설치물이 위 규칙에 어긋나면 삭제하지 않는다. -> 삭제 조건을 찾는 것이 관건인 문제
작업 결과는 x 좌표 오름차순 > y 좌표 오름차순 > 좌표가 같으면 기둥부터.
<br>
<br>
구현
<br>
기둥은 pillars, 보는 bridges에 설치 시작 좌표를 저장한다.
- 기둥의 설치 조건은 다음과 같다.
- y = 0이거나
- bridges[x-1][y] 또는 bridges[x][y]가 true거나
- pillars[x][y-1]가 true
- 보의 설치 조건은 다음과 같다.
- pillars[x][y-1] 또는 pillars[x+1][y-1])가 true거나
- bridges[x-1][y]와 bridges[x+1][y] 모두 true
- 기둥과 보를 삭제할 때는 처음에 삭제했다가
- 기둥은 왼쪽 위 보, 오른쪽 위 …

[공통 - Minseon] 60061

---

programmers/12907/Minseon_12907.java

**[프로그래머스 12907번](https://school.programmers.co.kr/learn/courses/30/lessons/12907)**
<br>
<br>
주어진 화폐 단위로 n원을 만들 수 있는 모든 경우의 수를 구하는 문제.
n이 최대 100000이므로 완전탐색으로는 풀 수 없다. -> dp로 풀기
<br>
<br>
DP
<br>
- dp[n] += dp[n-화폐단위]으로 표현할 수 있지만, 중복되는 경우가 발생할 수 있다.
- 화폐단위를 순회하며 현재 화폐단위에서 dp를 시작해서 중복을 방지한다.
ex) dp[1] ~ dp[n] -> 1로만 만들 수 있는 경우의 수 계산 (dp[1-1] ~ dp[n-1]에 1을 추가하는 것)
dp[2] ~ dp[n] -> 2를 추가했을 때 경우의 수 계산 (다른 경우가 계산된 dp[2-2] ~ dp[n-2]에 2를 추가하는 것)
dp[5] ~ dp[n] -> 5를 추가했을 때 경우의 수 계산 (다른 경우가 계산된 dp[5-5] ~ dp[n-5]에 5를 추가하는 것)
<br>
시간복잡도: 돈의 종류가 최대 100종류이므로 최악의 경우 O(n*100) => O(n)
공간복잡도: O(n)
<br>
<br>
처음에 for문 두 개를 반대로 배치했더니 중복되는 경우가 생겼음.
<br>
<br>
소요 시간 : 14분
<br/>

[개별 - Minseon] 12907

---

programmers/17687/Minseon_17687.java

**[프로그래머스 17687번](https://school.programmers.co.kr/learn/courses/30/lessons/17687)**
<br>
<br>
- n진수로 변환해서 본인의 차례 때 어떤 수를 말해야 하는지 구하는 문제
- 변환 결과가 2자리 이상인 경우 숫자를 풀어서 한 사람이 숫자 한 개를 말하는 규칙.
<br>
<br>
구현
<br>
- n진수를 변환하는 규칙에 맞게 메소드를 만든다.
- 계산 과정 중에 나머지가 10이상이면 아스키코드를 이용해 A~F로 변환한다.
- do-while문으로 몫이 0인 경우도 처리한다.
- 변환하는 수는 따로 규칙을 찾을까 했는데 크게 차이 안 날 거 같아서 그냥 최대 자리수인 t * m으로 설정한다.
- for문의 step 부분을 조정해서 튜브의 차례때만 문자열에 해당 숫자를 추가한다.
<br>
문자열 처리 과정에서 시간 단축을 위해 StringBuilder 사용
<br>
<br>
자바에서 진수변환하는 메소드가 있긴 한데 그건 너무 날먹이라 그냥 구현.
<br>
<br>
소요 시간 : 50분
<br/>

[공통 - Minseon] 17687

---

programmers/12941/Minseon_12941.js

**[프로그래머스 12941번](https://school.programmers.co.kr/learn/courses/30/lessons/12941)**
AI 추천 문제
<br>
<br>
A, B에서 각각 숫자 하나씩 곱해서 합을 구했을 때 최솟값을 구하는 문제.
<br>
<br>
정렬
<br>
- 최솟값을 만들기 위해서는 작은 수와 큰 수를 곱해야 한다.
- A는 오름차순, B는 내림차순 정렬해서 같은 인덱스끼리 곱해서 누적합을 구한다.
- js로 풀이하므로 sort()는 문자열 정렬이기 때문에 callback 함수를 이용한다.
<br>
O(NlogN)
<br>
<br>
이게 레벨 2?
<br>
<br>
소요 시간 : 5분
<br/>

[개별 - Minseon] 12941

---

programmers/68936/Minseon_68936.java

**[프로그래머스 68936번](https://school.programmers.co.kr/learn/courses/30/lessons/68936)**
<br>
<br>
쿼드 압축을 구현해서 최종적으로 압축된 결과를 출력하는 문제.
- 정사각형 범위 안에 있는 수가 모두 같으면 그 숫자로 압축
- 다르면 더 작은 정사각형 4개로 쪼개서 더 이상 쪼갤 수 없을 때까지 반복한다.
<br>
<br>
구현, 재귀
<br>
- 사각형을 계속 쪼개는 방식이므로 재귀함수로 구현한다.
- 사각형에 있는 수가 모두 같으면 해당 수에 +1
- 다르면 4개의 정사각형 배열로 나눠서 반복한다.
<br>
O(2^n)
<br>
<br>
<br>
<br>
소요 시간 : 21분
<br/>

[개별 - Minseon] 68936

---

programmers/169199/Minseon_169199.java

**[프로그래머스 169199번](https://school.programmers.co.kr/learn/courses/30/lessons/169199)**
<br>
<br>
- 목표 지점에 도달하는 최소 이동 횟수를 구하는 문제.
- 한 번의 이동은 벽이나 장애물을 만나지 않을 때까지 직진하는 것을 의미한다.
<br>
<br>
BFS
<br>
- 최소 이동 횟수를 구하는 문제이므로 bfs로 탐색한다.
- 클래스를 정의해서 현재 좌표와 이동 횟수를 저장한다.
- 벽이나 장애물을 만나지 않을 때까지 해당 방향으로 직진하는 함수를 만든다.
- 방문하지 않은 좌표만 큐에 추가해서 중복으로 해당 위치를 방문하지 않도록 한다.
<br>
O(nm)
<br>
<br>
<br>
<br>
소요 시간 : 54분
<br/>

[개별 - Minseon] 169199

---

programmers/42888/Minseon_42888.java

**[프로그래머스 42888번](https://school.programmers.co.kr/learn/courses/30/lessons/42888)**
<br>
<br>
닉네임 변경 내역을 반영한 최종 메시지를 변환하는 문제
- 닉네임 변경은 1) 들어오고 새로운 닉네임으로 들어오거나 2) 채팅창 내에서 변경할 수 있다.
- 어떤 유저의 닉네임이 변경되면 그 전 기록의 유저 닉네임도 변경한 닉네임으로 업데이트한다.
- 기록 형식은 "Enter/Leave/Change 유저ID 닉네임"의 형식
- 최종 메시지는 "[닉네임]님이 들어왔습니다." 또는 "[닉네임]님이 나갔습니다."의 형식
<br>
<br>
해시
<br>
- 유저id가 고유하므로 이를 key로 하고 닉네임을 value로 하는 해시맵을 만든다.
- 기록을 한 번 돌면서 enter 또는 change면 해당 key에 닉네임을 put하는 방식으로 최근 설정한 닉네임으로 업데이트한다.
- 기록을 다시 한 번 돌면서 닉네임은 해시맵에서 가져오고 enter, leave는 대응하는 메시지로 변환, change는 메시지를 변환하지 않는다.
<br>
O(n)
<br>
<br>
<br>
<br>
소요 시간 : 18분
<br/>

[공통 - Minseon] 42888

---

programmers/42628/Minseon_42628.java

**[프로그래머스 42628번](https://school.programmers.co.kr/learn/courses/30/lessons/42628)**
<br>
<br>
주어진 operation을 모두 수행했을 때 최댓값과 최솟값을 구하는 문제. 주어진 operation은 다음과 같다.
명령어 | 수신 탑(높이)
-- | --
I 숫자 | 큐에 주어진 숫자를 삽입합니다.
D 1 | 큐에서 최댓값을 삭제합니다.
D -1 | 큐에서 최솟값을 삭제합니다.
<br>
<br>
힙
<br>
- 힙의 자료구조 특성상 최소힙의 마지막 원소가 최댓값이라는 보장이 없다 -> 진짜 힙을 두 개 써야 함
- 우선 최소힙을 만들어 놓고 최댓값을 삭제하는 operation이 나오면 그때 최대힙을 만들어서 최댓값을 삭제한 후 그 결과를 다시 최소힙에 넣는다.
- 최댓값은 최대 힙에서, 최솟값은 최소 힙에서 poll
<br>
힙 자료구조에서 삽입과 삭제는 O(logN)이므로 최종 시간복잡도는 O(NlogN)
<br>
<br>
js로 풀어야지 했는데 자바로 풀어버렸네 아니 오히려 좋아 요즘 ts 공부중이니까 다음주부터 ts로 풀지 뭐
<br>
<br>
소요 시간 : 27분
이번주 ai가 추천해준 문제 풀었는데 나쁘지 않은듯. 소소하게 자랑을 하자면 저번주까지는 중위권이었는데 이번주에 상위권 그룹에 합류했다! 열심히 해서 더 오른쪽으로 가고 싶군
<br/>

[개별 - Minseon] 42628

---

programmers/42888/Yebin_42888.java

**[프로그래머스 42888번 오픈채팅방](https://school.programmers.co.kr/learn/courses/30/lessons/42888)**
<br>
<br>
- 오픈 채팅방의 출입 기록 메시지를 생성하는 문제
- 메시지마다 닉네임이 들어간다
- uid는 유니크하고 닉네임은 중복가능
- 닉네임은 1)입장할 때 2)채팅방 안에서 변경할 때 설정된다
- 채팅방 밖에서 닉네임을 변경한다던가 잘못된 입력이 들어오는 경우는 없다
<br>
<br>
- 해시
<br>
- 기록을 순회하며 닉네임과 출입기록 저장
- 출입기록을 저장할 리스트 생성
- 고유아이디를 키로 하는. Hash<uid, nickname>을 생성
- 채팅방에 입장하거나 닉네임 변경 시 해시맵에 저장 
- key로 저장하면 알아서 덮어쓰기 됨 
- 채팅방에 입장하거나 나갈 때 출입리스트에 저장
- 출입기록을 보고 메시지 생성
- 출입기록 길이와 같은 답 배열 생성
- 출입기록을 순회하며 답 배열에 매시지 저장 
<br>
- 시간복잡도 : 기록을 한번 순회해야 하므로 O(n)
- 공간복잡도 : 닉네임과 출입기록을 따로 저장하려 하므로 총합하면 O(n)을 사용하게 된다
<br>
<br>
❌ 
<br>
<br>
20분
<br/>

[공통 - Yebin] 42888

---

programmers/138476/Yebin_138476.java

**[프로그래머스 138476번 귤 고르기](https://school.programmers.co.kr/learn/courses/30/lessons/138476)**
귤먹고싶당
<br>
<br>
- 종류를 최소로 해야 하므로 최대한 갯수가 많은 걸 우선으로 선택하면 된다 
- 종류를 선택할 때 꼭 k개로 맞아 떨어져야 하는 건 아니다
- 종류 별 개수로 정렬하는 것이 관건
<br>
<br>
- 정렬
- 해시(종류로 검색하려고 씀)
<br>
- 종류 별 개수 세기
- 해시맵을 <종류, 개수>로 선언
- 개수로 내림차순 정렬
- 해시맵의 value를 기준으로 keySet을 정렬
- 개수가 많은 것을 우선으로 k개를 채움 
- 정렬된 keySet으로 해시맵 탐색
- k에 개수만큼 빼다가 0 이하면 선택을 멈춤
- 결과 반환
<br>
- 시간복잡도 : 일단 귤들을 한번 순회해야 하므로 O(k)
- 공간복잡도 : 귤의 종류만큼 개수 저장 맵이 커지므로 O(tan). tan은 귤의 종류(크기)
<br>
<br>
❌ 
<br>
<br>
10분 
<br/>

[개별 - Yebin] 138476

---

programmers/150369/Minseon_150369.java

**[프로그래머스 150369번](https://school.programmers.co.kr/learn/courses/30/lessons/150369)**
<br>
<br>
트럭에 최대 실을 수 있는 박스의 개수가 있고 배달 및 수거를 모두 할 수 있는 최소 이동 거리를 찾는 문제.
- 갈 때는 cap개 만큼 배달하고 올 때 cap개 만큼 수거하면 된다. => 이동 거리를 최소화하려면 가장 먼 곳부터 갖다 와야 한다.
- 한 번의 이동에 대한 회차 위치를 어떻게 찾을 것인지가 포인트.
<br>
<br>
스택
<br>
- 배달 위치를 저장하는 스택과 수거 위치를 저장하는 스택을 만든다.
- 해당 인덱스의 상자의 개수만큼 그 인덱스를 각 스택에 넣는다. -> 스택은 LIFO이므로 0부터 시작
ex) 5번 인덱스에 상자가 2개 있다면 stack.push(5)를 두 번 실행한다.
- 두 스택이 모두 빌 때까지 cap만큼 pop한다. 이때 회차 위치는 pop하기 전 stack.peek()에 저장된 위치가 된다.
<br>
O(n+m)
<br>
<br>
그리디로 풀었다가 테케 17번 시간 초과를 해결 못해서 반례 찾다가 스택으로 푸는 방법이 있길래 스택으로 바꿨다.
- 그리디로 풀었을 때 회차 위치를 뒤에서 부터 for문으로 탐색해서 deliveries[i] 또는 pickups[i] 중 하나라도 0보다 크면 그 위치를 회차 위치로 지정하는 방식으로 했는데 이 과정에서 시간복잡도가 O(n^2)가 되면서 …

[공통 - Minseon] 150369

---

programmers/12929/Minseon_12929.java

**[프로그래머스 12929번](https://school.programmers.co.kr/learn/courses/30/lessons/12929)**
<br>
<br>
주어진 괄호 쌍으로 모든 올바른 괄호 쌍을 만들 수 있는 경우의 수를 구하는 문제
-> 처음에는 완전탐색을 해야 되나 했는데, 그려보다보니 dp로 풀 수 있을 것 같았다.
<br>
<br>
dp
<br>
- 올바른 괄호 쌍을 만들기 위한 조건을 바탕으로 점화식을 만들었는데 예시로 설명하는 게 더 편할 것 같다.
```
예를 들어 4개의 괄호 쌍으로 만들 수 있는 올바른 괄호 쌍은 다음과 같다.
1개의 괄호쌍 + 3개의 괄호쌍
2개의 괄호쌍 + 2개의 괄호쌍
3개의 괄호쌍 + 1개의 괄호쌍
4개의 괄호쌍 + 0개의 괄호쌍
이는 다음과 같이 표현할 수 있다.
( 0개의 괄호쌍 ) + 3개의 괄호쌍 ex. ()(()()) => dp[0] * dp[3]
( 1개의 괄호쌍 ) + 2개의 괄호쌍 ex. (())()()  => dp[1] * dp[2]
( 2개의 괄호쌍 ) + 1개의 괄호쌍 ex. (()())()  => dp[2] * dp[1]
( 3개의 괄호쌍 ) ex. (()()())  => dp[3] * dp[0]
```
따라서 점화식을 구하면
dp[i+1] = SUM(dp[j] * dp[i-j]) (j = 0, 1, 2, ... , i)
<br>
O(n^2)지만 n의 최댓값이 14이므로 사실상 상수 시간이다. dp 이즈 갓 …

[개별 - Minseon] 12929

---

programmers/12942/Minseon_12942.java

**[프로그래머스 12942번](https://school.programmers.co.kr/learn/courses/30/lessons/12942)**
<br>
<br>
- 행렬의 연산 순서가 주어지면 결합 법칙을 이용해서 연산 횟수를 최소로 만드는 문제.
- AxB 행렬과 BxC 행렬의 곱 연산 횟수는 A * B * C이다.
근데 문제 조건이 좀 불친절한 느낌. matrix_sizes에 대한 조건이 모호했지만 다른 사람들이 순서대로 풀었다길래 나도 순서대로 풀었음.
+) 알면 좋은 것: AxB 행렬과 BxC 행렬의 곱 결과는 AxC 행렬 -> 근데 이거도 문제에서 안 알려줌
<br>
<br>
수학(행렬 곱셈), 재귀, dp
<br>
- 행렬의 곱은 결국 두 행렬 덩어리를 곱하는 것
- i~j번째 행렬의 곱 연산 횟수는 k번째에서 두 덩어리로 나눴을 때, i~k번째 행렬의 곱 연산 횟수 + k+1~j번째 행렬의 곱 연산 횟수 + 두 행렬 덩어리의 곱 연산 횟수가 된다.
- 이를 점화식으로 나타내면 dp[i][k] + dp[k+1][j] + matrix_sizes[i][0] * matrix_sizes[k][1] * matrix_sizes[j][1]
- 이 식에서 dp[i][k]와 dp[k+1][j]를 구하는 과정을 재귀로 구현한다. 더 이상 쪼갤 수 없을 때까지.
- 이때, i == j이면 같은 행렬끼리는 연산할 수 없으므로 dp[i][j] = 0
<br>
top-down 방식으로 구현해서 …

[개별 - Minseon] 12942

---

programmers/42892/Minseon_42892.java

**[프로그래머스 42892번](https://school.programmers.co.kr/learn/courses/30/lessons/42892)**
<br>
<br>
이진 트리를 구현하고 전위 순회, 후위 순회하는 문제.
<br>
<br>
트리
<br>
- 주어진 좌표들을 y좌표 > x좌표 순으로 정렬한다. -> 우선순위 큐 이용 => 루트 노드 찾기
- 노드와 이진트리 클래스를 구현해서 정렬한 좌표 순서대로 이진트리에 insert한다.
- 만든 이진트리에 대해 전위 순회, 후위 순회를 한다.
<br>
O(NlogN)
<br>
<br>
트리 자료구조 구현하는 건 뭔가 오랜만인 느낌? 근데 생각해보니까 루트 노드만 찾고 노드 정렬은 안 해도 됐을 것 같다.
<br>
<br>
소요 시간 : 54분
<br/>

[공통 - MInseon] 42892

---

programmers/42884/Minseon_42884.java

**[프로그래머스 42884번](https://school.programmers.co.kr/learn/courses/30/lessons/42884)**
<br>
<br>
차량의 진입 지점과 진출 지점이 주어지면 모든 차량이 단속카메라를 지나갈 수 있도록 하는 단속 카메라의 최소 개수를 구하는 문제.
<br>
<br>
그리디
<br>
- 진출 지점을 기준으로 routes를 정렬하여 큐에 넣는다.
- 가장 빠른 진출 지점에 카메라를 설치해야 첫번째로 나가는 차량이 단속카메라를 지나갈 수 있다.
- 카메라를 설치하고 해당 지점을 지나는 모든 차량을 poll한다.
- 해당 지점을 지나지 않는 차량이 나오면 그 차량의 진출 지점에 카메라를 설치하고 앞의 과정을 반복한다.
<br>
O(NlogN)
<br>
<br>
처음에 진입 지점을 기준으로 정렬했는데 첫번째로 진입하는 차량이 가장 먼저 나가지는 않는다는 점을 간과했었다.
<br>
<br>
소요 시간 : 30분
<br/>

[개별 - Minseon] 42884

---

programmers/150369/Yebin_150369.java

**[프로그래머스 150369번 택배 배달과 수거하기](https://school.programmers.co.kr/learn/courses/30/lessons/150369)**
<br>
<br>
- 트럭 용량만큼만 배달/수거 할 수 있다.
- 한번에 가능한 한 많이 배달하고 가능한 한 많이 수거해오면 된다. -> `Greedy`
- 길이 일직선이므로 이동한 거리는 제일 멀리간 거리 * 2로 계산할 수 있다.
<br>
<br>
- 그리디
- 스택
<br>
- 배달/수거 스택 만들기
- 배달/수거할 장소의 인덱스를 담는 스택을 각각 생성.
- 위로 갈수록 인덱스가 커지도록 한다.
- 최대한 멀리 가서 최대한 많이 배달/수거하기
- pop
- 제일 멀리 간 거리 저장(인덱스의 최댓값)
- 트럭 용량 - 배달/수거할 상자들
- 용량이 음수가 되면 배달/수거를 다 하지 못했다는 뜻.
- 스택에 다시 인덱스를 넣어준다.
- 상자 배열 업데이트 
- 결과 출력
<br>
- 시간복잡도 : 배달/수거 스택을 만들기 위해 순회를 한번 해야 하므로 O(n)
- 공간복잡도 : 배달/수거 스택을 사용하니 O(n)
<br>
<br>
- 그리디하게 풀어도 된다는건 빠르게 파악했는데 최대한 멀리 가서 배달/수거하는 걸 구현하는데 오래걸림 
- 모든걸 인덱스 변수를 조작해서 풀려다가 구현이 어지러워져서 초기화하고 스택을 활용함.
<br>
<br>
1시간 30분
<br/>

[공통 - Yebin] 150369

---

programmers/42892/Yebin_42892.java

**[프로그래머스 42892번 길 찾기 게임](https://school.programmers.co.kr/learn/courses/30/lessons/42892)**
<br>
<br>
- 결국 트리를 전위/후위 순회를 하는 문제
- 단, 좌표를 보고 그래프를 직접 만들어야 한다.
- 전에 @SoleiI 이가 python으로 Node를 만들고 트리인가 그래프를 직접 만들어서 문제를 풀었던게 기억남. 
<br>
<br>
- 트리 탐색
- 정렬
<br>
- 이진트리 만들기
- 노드번호, 좌표, 왼/오 노드를 저장할 클래스 선언
- 좌표로 정렬하기 위해 노드를 리스트로 저장
- y가 제일 큰 게 루트 노드이므로 y를 기준으로 정렬 
- 리스트를 순회하며 루트 노드에 연결
- x 좌표가 루트의 x보다 작으면 왼쪽, 아니면 오른쪽
- 왼쪽/오른쪽에 이미 노드가 있으면 그 이하로 내려간다. 이미 y로 정렬했기 때문에 무조건 내려가면 올바른 레벨로 가게 됨.
- 전위/후위 순회
- 하면 됨
- 결과 출력
<br>
- 시간복잡도 : 이진 트리의 순회 시간 복잡도 O(log n).
- 공간복잡도 : 트리 높이가 최대 10^3이라는 힌트가 이정도면 전위/후위 순회에 스택 메모리는 문제 없다는 힌트라고 생각했음. 노드 리스트와 전위/후위 순회 결과를 저장하는 힙 메모리는 O(n). n은 노드의 개수.
<br>
<br>
<br>
<br>
58분
+ 마지막에 결과를 가공하는 부분을 단순 반복문에서 stream으로 …

[공통 - Yebin] 42892

---

swea/1225/Yebin_1225.java

**[SWEA 1225. [S/W 문제해결 기본] 7일차 - 암호생성기 D3](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AV14uWl6AF0CFAYD&categoryId=AV14uWl6AF0CFAYD&categoryType=CODE&problemTitle=&orderBy=PASS_RATE&selectCodeLang=JAVA&select-1=3&pageSize=20&pageIndex=1)**
<br>
<br>
- 테스트 케이스 10개, 숫자 8개, 한 사이클에 5개 감소시키는 것이 정해져 있음
- 숫자를 감소시키다가 0보다 작아지면 0을 넣고 종료
<br>
<br>
- 구현
<br>
- 입력
- 맨 앞을 빼서 맨 뒤로 보내야 하므로 LinkedList로 저장
- 암호 생성
- 1~5를 감소시키는 것을 한 사이클로 항상 맨 앞의 것을 제거해서 감소시킨 뒤 맨 뒤에 붙이면 됨
- 출력
<br>
- 시간복잡도 : while문이라 잘 모르겠음...
- 공간복잡도 : O(1)
<br>
<br>
❌ 
<br>
<br>
18분
- 제출 결과 보면 다른 사람들 100ms대가 많이 나온다. 이걸 어케 줄인겅미?
<br/>

[개별 - Yebin] 1225

---

swea/1206/Yebin_1206.java

**[SWEA 1206. [S/W 문제해결 기본] 1일차 - View D3](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AV134DPqAA8CFAYh&categoryId=AV134DPqAA8CFAYh&categoryType=CODE&problemTitle=view&orderBy=PASS_RATE&selectCodeLang=ALL&select-1=3&pageSize=30&pageIndex=1)**
- SWEA D3 = 프로그래머스 L2 ?
<br>
<br>
- 조망권이 확보된 세대는 좌우로 2칸의 빌딩의 최대 높이보다 높은 세대 
<br>
<br>
- 구현
<br>
- 입력 
- 빌딩 높이 배열 생성
- 조망권 확보 세대 카운트
- 좌우+-2 안의 빌딩 최대 높이를 구해서 뺀 만큼
- +-2 영역 안의 빌딩 최대 높이보다 낮다면 조망권이 확보된 세대는 없다
- 출력
<br>
- 시간복잡도 : 각 빌딩 마다의 조망권이 확보된 세대를 구해야 하므로 O(n)
- 공간복잡도 : 빌딩의 높이를 저장하므로 O(n)
<br>
<br>
❌ 
<br>
<br>
15분
<br/>

[개별 - Yebin] 1206

---

swea/1220/Yebin_ 1220.java

**[SWEA 1220. [S/W 문제해결 기본] 5일차 - Magnetic D3](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV14hwZqABsCFAYD)**
<br>
<br>
- 어떤 행에서 교착상태가 되는지는 중요하지 않다
- 열마다 1이 2와 몇번 만나는지를 확인하면 된다
<br>
<br>
- 구현 
- 이번주엔 D3의 정답률 순으로 풀었는데 알고리즘 보단 자료구조 잘 선택해서 적당히 구현하는 문제가 많은 것 같다.
<br>
- 입력
- 교착상태 개수 세기
- 한 열씩 확인한다
- 1(RED)이 2(BLUE)와 몇번 매칭되는지 카운트
- 출력
- StringBuffer 사용
<br>
- 시간복잡도 : 항상 100 * 100 *10
- 공간복잡도 : 항상 100 * 100
<br>
<br>
- 떨어질 걸 제거한 뒤 카운트를 했었는데 다 풀고 보니 어차피 매칭되는 걸 세면 떨어지는 건 세어지지 않는 것이었다. 
- 각 동작의 결과를 더 구체적으로 생각해야겠다.
<br>
<br>
40분
<br/>

[개별 - Yebin] 1220

---

programmers/42890/Minseon_42890.java

**[프로그래머스 42890번](https://school.programmers.co.kr/learn/courses/30/lessons/42890)**
<br>
<br>
릴레이션이 주어지면 유일성과 최소성을 만족하는 후보키의 개수를 구하는 문제.
- 유일성은 릴레이션에 있는 모든 튜플에 대해 유일하게 식별할 수 있어야 함을 의미하고,
- 최소성은 유일성을 가진 키를 구성하는 속성 중 하나라도 제외하는 경우 유일성이 깨짐을 의미한다.
<br>
<br>
완전 탐색
<br>
- 재귀를 이용해서 만들 수 있는 모든 키(중복되지 않는 속성 조합)를 만든다. 이때, 속성의 이름이 따로 주어지지 않으므로 인덱스를 조합한다.
- 유일성을 판별하는 isUnique와 최소성을 판별하는 isMinimal 메소드를 만들어서 두 조건을 모두 만족하는 키만 후보키 리스트에 추가한다.
- isUnique
- 키에 포함된 인덱스에 해당되는 column만 모아서 set을 이용해서 중복을 제거한 리스트를 만든 다음 원래 relation과의 크기를 비교한다.
- 크기가 같으면 해당 키로 튜플을 식별할 수 있다는 의미가 된다. 크기가 다른 경우 중복이 있으므로 식별할 수 없다.
- isMinimal
- 만들 수 있는 모든 키 리스트에는 키의 크기가 작은 순서대로 들어가 있으므로 유일성을 만족하는 키를 구성하는 작은 단위의 키가 후보키에 있을 수 있다.
- 후보키에 포함된 키가 현재 키에 포함되어 있다는 것은 현재 키에 포함된 다른 속성을 제거하더라도 유일성이 깨지지 않는다는 …

[공통 - Minseon] 42890

---

programmers/68646/Minseon_68646.java

**[프로그래머스 68646번](https://school.programmers.co.kr/learn/courses/30/lessons/68646)**
<br>
<br>
일렬로 번호가 써있는 풍선을 규칙에 맞춰 터트렸을 때, 최후에 남을 수 있는 풍선의 개수를 구하는 문제. 규칙은 다음과 같다.
```
1. 임의의 인접한 두 풍선을 고른 뒤, 두 풍선 중 하나를 터트립니다.
2. 터진 풍선으로 인해 풍선들 사이에 빈 공간이 생겼다면, 빈 공간이 없도록 풍선들을 중앙으로 밀착시킵니다.
```
이때, 두 풍선 중 하나를 터트릴 때는 더 큰 수가 적힌 풍선을 터트려야 하며, 단 한 번 더 작은 수가 적힌 풍선을 터트릴 수 있다.
<br>
<br>
구현, 약간의 dp
<br>
더 작은 풍선을 터트릴 수 있는 기회가 한 번 뿐이라는 것은 자신이 최솟값이거나 왼쪽에 있는 풍선 중에, 또는 오른쪽에 있는 풍선 중에 자신보다 작은 풍선이 없으면 살아남을 수 있다는 이야기가 된다. 나보다 작은 번호의 풍선이 있으면 그 풍선에 의해 제거될 수 있기 때문이다.
- 자신을 포함해서 왼쪽에 있는 풍선 중 최솟값을 저장하는 배열 leftMin과 오른쪽에 있는 풍선 중 최솟값을 저장하는 배열 rightMin을 만든다.
- 가장 왼쪽에 있는 풍선은 왼쪽에 아무도 없기 때문에 자신의 숫자를 최솟값으로 갖는다. leftMin[0] = a[0]
- 마찬가지로 rightMin[a.length-1] = a[a.length-1]
- 반복문을 이용해서 leftMin[i]과 …

[개별 - Minseon] 68646

---

programmers/17678/Minseon_17678.java

**[프로그래머스 17678번](https://school.programmers.co.kr/learn/courses/30/lessons/17678)**
<br>
<br>
09:00부터 t분 간격으로 n회 운행하는 m인승 버스에 대기 중인 크루를 태우고 갈 때, 콘이 버스를 타고 갈 수 있는 가장 늦은 도착 시각을 구하는 문제.
- 버스는 버스 출발 시각까지 대기열에 도착한 크루를 태울 수 있다.
- 대기열 순서대로 탑승한다.
<br>
<br>
구현
<br>
1. 대기열 순서대로 태우고 가므로 도착 시각 순서대로 정렬해서 deque에 넣는다.
- deque 자료구조를 이용해 큐를 이용하면서 addFirst를 이용해 poll한 값도 다시 deque에 넣을 수 있도록 한다.
2. 셔틀버스 시간표를 만든다.
- 주어진 t를 이용해서 t분 간격으로 길이 n의 셔틀버스 시간표 배열을 생성한다. 이때 첫번째 원소는 무조건 09:00
3. 마지막 버스의 탑승객 수와 마지막 탑승객의 도착 시각을 구한다.
- 도착한 버스에 탑승할 수 있는 크루를 정원만큼 태우면서 마지막에 탑승한 승객의 도착 시각을 변수에 저장한다.
- 마찬가지로 버스에 탑승할 수 있는 크루를 태우면서 현재 버스에 탑승한 승객의 수를 변수에 저장한다.
4. 콘의 도착 시각 구하기
- 콘이 제일 늦게 도착할 수 있는 경우는 가장 마지막에 도착하는 버스의 출발 시각에 대기열에 도착하거나 가장 마지막에 탑승한 승객보다 1분 일찍 도착하면 된다(도착 시각이 같으면 무조건 제일 뒤로 밀려 정원이 다 …

[공통 - Minseon] 17678

---

programmers/12938/Minseon_12938.java

**[프로그래머스 12938번](https://school.programmers.co.kr/learn/courses/30/lessons/12938)**
<br>
<br>
각 원소의 합이 s이면서 각 원소의 곱이 최대가 되는 자연수 n개의 중복 집합을 구하는 문제.
- 집합의 원소는 오름차순 정렬이다.
- n과 s의 최댓값이 매우 크므로 완전탐색으로는 풀 수 없음.
<br>
<br>
그리디
<br>
모든 원소를 s/n에 최대한 가깝게 구성했을 때 곱한 값이 최대가 될 것 같았다.
- s/n이 1보다 작으면(n이 s보다 크면) 각 원소의 합이 s인 집합을 만들 수 없으므로 -1 리턴
- 집합에 그 순간 넣을 수 있는 최댓값(s/n)을 넣는다.
<br>
O(n)
<br>
<br>
이왜렙3?
<br>
<br>
소요 시간 : 12분
<br/>

[개별 - Minseon] 12938

---

programmers/86053/Minseon_86053.java

**[프로그래머스 86053번](https://school.programmers.co.kr/learn/courses/30/lessons/86053)**
<br>
<br>
새로운 도시에 금 akg, 은 bkg이 필요한데 각 도시에서 각 도시와 새로운 도시만을 이동하는 트럭으로 옮겨서 조달할 때 최소 소요 시간을 구하는 문제
- 각 도시의 금, 은 보유량은 각각 배열 g, s로 주어진다.
- 각 도시와 새로운 도시를 오가는 트럭의 편도 이동시간과 최대 적재량은 각각 배열 t, w로 주어진다.
- 각 배열의 크기가 최대 10e5 -> 매우매우매우매우 크다....
<br>
<br>
이분 탐색
<br>
- mid = 소요 시간으로 정의한다.
- right 값은 금과 은의 최대 무게 합 * 트럭의 최대 왕복 이동 시간
- 해당 시간동안 새로운 도시에 갖다 놓을 수 있는 금과 은의 무게를 구한 뒤 그 무게가 a, b보다 크거나 같으면 right = mid
<br>
O(logN)
<br>
<br>
최댓값이 너무 커서 처음에 어떻게 접근해야 하나 고민했는데 다른 사람들이 이분탐색으로 풀었더라. 그래서 아! 이분탐색이 있었지! 했다. 이분탐색 좀 더 연습해야 될 듯
<br>
<br>
소요 시간 : 54분
<br/>

[개별 - Minseon] 86053

---

programmers/17678/Yebin_17678.java

**[17678번 셔틀버스](https://school.programmers.co.kr/learn/courses/30/lessons/17678)**
<br>
<br>
- 출력 : 최대한 늦게 셔틀을 타기 위한 도착 시간
- 입력 : 셔틀 운행 횟수, 셔틀 운행 간격, 셔틀 수용 인원, 크루 도착 시간
- 운행 간격이 분단위로 들어온다. 시간도 분단위로 맞추면 계산이 편할 것. 
- 크루 도착 시간을 정렬해야 대기 순서을 알 수 있겠다. 
- 모든 사원을 태우는게 중요한 게 아니라 콘이 차에 탈 수 있는지가 중요함. 
<br>
<br>
- 완전탐색
<br>
- 시간 포맷 
- 시각을 분 단위로 변환 
- 대기열 생성
- 도착 시간 순서대로 버스를 타야 하므로 정렬하고 큐에 넣는다 
- 셔틀 운행 
- 셔틀 용량을 최대한 채운다 
- 셔틀이 다 찼을 땐 맨 마지막 사람보다 1분만 일찍 와도 셔틀을 탈 수 있다
- 셔틀이 다 안찼을 땐 셔틀 시간에 맞춰오면 탈 수 있다
- 모든 셔틀 운행 스케쥴에 대해 셔틀에 탈 수 있는 가장 늦은 시간을 알아본다 
- 제일 늦은 시간 출력 
<br>
- 시간복잡도 : 대기열을 한 번 순회하므로 O(n)
- 공간복잡도 : 대기열 리스트 O(n)
<br>
<br>
<br>
<br>
34분
<br/>

[공통 - Yebin] 17678

---

programmers/77885/Yebin_77885.java

**[77885번 2개 이하로 다른 비트](https://school.programmers.co.kr/learn/courses/30/lessons/77885)**
<br>
<br>
- 비트를 0->1 로 많이 바꿀수록 수가 커지므로 비트를 최대한 덜 바꾸는 게 좋음 
- 짝수일 땐 가장 작은 비트가 0이므로 +1 해주면 다음 홀수가 된다
```
0010 = 2
+ 0001
---
0011 = 3
```
- 홀수일 땐 가장 작은 0 비트가 있는 위치 바로 오른쪽에 +1 해준만큼 차이가 남 
``` 
0111 = 7
+ 0100
---
1011 = 11
```
<br>
<br>
- 비트 연산
- 그리디
<br>
- 함수 f(x) 선언
- 짝수면 1자리의 비트를 `0->1`로 바꿈 (= 1을 더함)
- 홀수면 가장 낮은 0 비트를 찾아서 바로 밑 비트를 `0->1`로 바꿈 
```
0111 & 1 = 0001
0111 & 10 = 0010
0111 & 100 = 0100
0111 & 1000 = 0000 ⭐ 0비트 찾음
```
- 입력된 수에 대해 함수 실행
- 여러개의 입력에 대해 함수 결과를 담아서 반환 
<br>
<br>
<br>
- 비트 연산을 오랜만에 해봐서 &, <<, >> 연산들을 떠올리는데 좀 걸림
- 비트 연산에 더해 비트마스킹도 연습해보면 좋겠다
<br>
<br>
45분
<br/>

[개별 - Yebin] 77885

---

programmers/92335/Yebin_92335.java

**[92335번 k진수에서 소수 개수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)**
<br>
<br>
- 소수를 찾기 전에 먼저 k진수로 변환해야 한다. -> Java API `Integer.toString(수, 진법)` 
- 조건에 맞는 10진수를 걸러냄 
```
437674 = 211020101011(3) 에서 위치 조건이 맞는 수는
211, 2, 1, 1, 11
== 0을 기준으로 split 한 결과
```
- 그리고 그 수들이 소수인지 확인하는 문제
<br>
<br>
- 수학
- 완전탐색?
<br>
- k진수로 변환
- 변환된 수를 0을 기준으로 자름
- 소수 판별 
- 1은 소수 아님
- N의 제곱근보다 작은 자연수로 모두 나눠보기
- 나눠지는 수가 하나라도 있으면 소수 아님
<br>
- 시간복잡도 : 영역 내 모두 같은 수인지 확인하는게 2중 반복문이지만 영역이 기하급수적으로 작아짐. O(log n)
- 공간복잡도 : 영역의 최대 크기가 1024=2^10 이므로 재귀 최대 깊이 10. 최종적으로 남는 0과 1을 세는 배열 하나 있으므로 O(1).
<br>
<br>
- 진법 변환을 일일이 구현하기 싫어서 진법 변환 함수 찾아봄... 😄 
<br>
<br>
20분
<br/>

[개별 - Yebin] 92335

---

programmers/42861/Minseon_42861.java

**[프로그래머스 42861번](https://school.programmers.co.kr/learn/courses/30/lessons/42861)**
<br>
<br>
간선 정보가 주어지면 모든 정점을 연결하고 사이클이 생기지 않는 최소 비용이 드는 간선을 선택해 그 비용을 모두 더하는 문제
<br>
<br>
크루스칼
<br>
Union-Find를 활용한다. 그 중 크루스칼 알고리즘
- 최소 비용 순으로 정렬한다.
- 순서대로 선택하며 부모가 같지 않으면 연결되어 있지 않다는 뜻이므로 union하고 비용을 더한다.
<br>
N을 costs의 길이라고 하면, O(NlogN)
<br>
<br>
다익스트라로 했다가 막혀서 크루스칼로 바꿨다.
<br>
<br>
소요 시간 : 52분
<br/>

[공통 - Minseon] 42861

---

programmers/250136/Minseon_250136.java

**[프로그래머스 250136번](https://school.programmers.co.kr/learn/courses/30/lessons/250136)**
<br>
<br>
석유가 여러 개의 덩어리로 구성되어 있을 때, 열 하나에서 뽑을 수 있는 석유량의 최댓값을 구하는 문제.
- 시추관이 어떤 덩어리를 지나면 그 덩어리에 있는 석유는 모두 뽑는다. (아래 그림 참고)
<br>
<br>
bfs
<br>
- bfs를 이용해서 덩어리의 크기와 덩어리에 포함된 열을 구한다.
- 이때, 열을 구할 때는 큐에서 나온 열을 리스트에 넣되, 그 리스트는 중복되지 않아야 하므로 Set을 이용한다. 
- bfs를 마친 후 덩어리에 포함된 열에 덩어리의 크기를 더한다. -> 해시를 이용해서 열마다 뽑을 수 있는 석유량 저장
- 모든 덩어리를 탐색했으면, 저장한 열마다 뽑을 수 있는 석유량의 최댓값을 구한다.
<br>
O(nm)
<br>
<br>
처음에 시추관을 뚫을 때마다 덩어리의 크기를 dfs로 구하는 방식으로 풀었는데 정확도 테스트는 통과했는데 효율성 테스트에서 전부 시간 초과가 떴다. n, m의 최댓값이 500이었기 때문에 land를 여러 번 탐색하면 시간 초과가 났던 것이다. 덩어리의 크기를 저장해서 그 크기를 이용하는 것이 핵심인 문제였다.
<br>
<br>
소요 시간 : 50분
<br/>

[공통 - Minseon] 250136

---

programmers/12987/Minseon_12987.java

**[프로그래머스 12987번](https://school.programmers.co.kr/learn/courses/30/lessons/12987)**
<br>
<br>
- 두 팀으로 나눠서 숫자 게임을 하는데, 이때 팀원들은 무작위의 수를 받는다.
- 팀원 한 명씩 순서대로 나와서 수를 비교한 다음 더 큰 수를 가진 팀이 승점 1점을 획득한다.
- A팀의 순서가 정해져 있을때 B팀의 최대 승점을 구하는 문제.
<br>
<br>
그리디
<br>
흑과 백 게임의 전략과 유사하다. 많이 이기기 위해서는 적은 차이로 승리하고, 질 때 많은 차이로 지면 된다.
- A팀 배열을 오름차순으로 정렬한다.
- B팀 배열도 오름차순으로 정렬하되, 절대 이길 수 없는 사람을 게임에서 제외하기 위해 poll을 쓸 수 있는 PriorityQueue로 정렬한다.
- A팀이 한 명씩 나올 때, B팀은 그 팀원을 이길 수 있는 가장 작은 수를 가진 사람이 나가서 승점을 획득한다. 즉, 승점을 획득할 수 있는 팀원이 나올 때까지 승점을 획득할 수 없는 팀원은 모두 poll한다.
- poll 해버리는 이유는 A팀에서 나온 팀원은 남은 팀원 중 가장 작은 수를 가진 사람인데 못 이기면 나머지도 못 이기기 때문.
<br>
O(NlogN)
<br>
<br>
이왜렙3?
<br>
<br>
소요 시간 : 26분
<br/>

[개별 - Minseon] 12987

---

programmers/49995/Minseon_49995.java

**[프로그래머스 49995번](https://school.programmers.co.kr/learn/courses/30/lessons/49995)**
<br>
<br>
첫째 아들이 l\~m번째 바구니, 둘째 아들이 m+1\~r번째 바구니를 가져가고, 각각 바구니에 들은 과자 수의 합이 같도록 할 때, 과자 수의 최댓값을 구하는 문제
<br>
<br>
투포인터
<br>
- m을 0~n-1까지 돌면서 l과 r을 양쪽 누적합이 같아질 때까지 이동하며 누적합을 구한다.
- 이때 왼쪽 누적합은 l~m까지의 합, 오른쪽 누적합은 m+1~r까지의 합
- 한쪽의 누적합이 최대 과자 개수 / 2보다 커지면 과자의 개수가 같아질 수 없으므로 넘어간다.
- 양쪽 누적합이 같아도 그보다 더 이동했을 때 또 누적합이 같아지는 경우가 있을 수 있으므로 l, r이 모두 양쪽 끝으로 갈 때까지 누적합을 구하는 과정을 반복한다.
<br>
O(n^2)
<br>
<br>
if문을 너무 남발해서 리팩토링이 필요한가 싶긴 한데 이왜렙4?
<br>
<br>
소요 시간 : 53분
<br/>

[개별 - Minseon] 49995

---

programmers/12973/Minseon_12973.java

**[프로그래머스 12973번](https://school.programmers.co.kr/learn/courses/30/lessons/12973)**
<br>
<br>
같은 문자 2개가 붙어있으면 계속 제거하고 남은 문자열을 합치는 과정을 반복하면서 문자열을 모두 제거할 수 있는지 구하는 문제.
<br>
<br>
스택
<br>
- for문으로 문자를 하나씩 돌면서 스택이 비어있으면 문자 push
- 스택 맨 위에 있는 문자가 현재 문자와 같으면 pop, 같지 않으면 현재 문자 push
- for문이 끝났을 때 스택이 비어있으면 성공
<br>
O(n)
<br>
<br>
처음에 substring으로 풀었다가 문자열의 길이가 최대 1,000,000인 걸 보고 스택으로 바꿨다.
<br>
<br>
소요 시간 : 14분
<br/>

[공통 - Minseon] 12973

---

programmers/42861/Yebin_42861.java

**[42861번](https://school.programmers.co.kr/learn/courses/30/lessons/42861)**
<br>
<br>
- 크루스칼 알고리즘을 이용하여 모든 노드를 연결하는 최소 비용 계산 => `MST 최소 신장 트리`
<br>
<br>
- kruskal
<br>
- 다리를 비용을 기준으로 정렬
- 크루스칼 알고리즘 이용
- 가장 비용이 작은 다리부터 
- 집합이 아니면 집합으로 만듬
- 집합이면 사이클이 생기므로 건너뜀
- 최소 비용 반환
- 집합을 생성하면서 쓴 다리의 비용을 누적합
<br>
- 시간복잡도 : 다리를 선형탐색 하므로 n, find 연산 1, union 연산 1 따라서 O(n)
- 공간복잡도 : 집합 표현 배열 O(n)
<br>
<br>
- 첨에 걍 그리디로 구현하다 뭔가 이상하다는 점을 깨달음. 모든 노드를 연결해야 하므로 집합 확인이 필요하다! 
<br>
<br>
34분
<br/>

[공통 - Yebin] 42861

---

programmers/17687/Yebin_17687.java

**[17687번](https://school.programmers.co.kr/learn/courses/30/lessons/17687)**
<br>
<br>
- 0부터 숫자를 n진수로 변환한다.
- m명의 사람을 순서대로 도는 것을 반복한다.
- t번 반복하는 동안 자기 차례 p에 숫자를 저장해야 한다.
<br>
<br>
- 문자열 처리(진법 변환)
- Queue
<br>
- m명의 사람을 t번 순회함
- 큐에서 숫자를 뽑고 p번째 차례라면 그 숫자를 저장
- 숫자는 0부터 시작한다
- 큐가 비어있을 때 숫자를 n진법 변환하여 문자 하나하나를 큐에 넣는다
- 큐에서 문자를 뽑고 
- 자기 순서가 맞으면 리스트에 추가
- 리스트를 문자열로 합쳐서 반환
- `String.join(필러, 배열);`
<br>
- 시간복잡도 : 모든 사람m에 대해 t번 반복하니까 O(m*t);
- 공간복잡도 : t개의 문자를 저장하게 됨 O(t);
<br>
<br>
<br>
<br>
25분
<br/>

[개별 - Yebin] 17687

---

programmers/17686/Yebin_17686.java

**[17686번](https://school.programmers.co.kr/learn/courses/30/lessons/17686)**
<br>
<br>
- 파일명의 HEAD, NUMBER을 기준으로 정렬하는 문제
- HEAD, NUMBER을 추출하기 위해 문자열을 다뤄야 함
- String[]에 담겨 있으므로 Arrays.sort를 쓸 수 있음 
- Comparator interface 의 compare을 구현해야 함 
<br>
<br>
- 정렬
- 문자열 처리
<br>
- 문자열 처리
- String.charAt(인덱스)를 이용해 숫자가 나오기 전까지를 HEAD, 다시 문자가 나오기 전까지를 NUMBER로 저장한다. `Character.isDigit(fileName(idx))`
- 인덱스가 문자열의 범위를 넘지 않는지 체크 `idx < fileName.length()`
- StringBuilder를 사용해서 문자열 생성 시간 단축 
- 정렬
- Arrays.sort(files, new Comparator<String>() { 여기에  compare 오버라이딩 } );
- compare는 비교하려는 객체들 중 앞이 크면 양수, 뒤가 크면 음수가 나와야 한다.
- 먼저 HEAD를 소문자로 만들고 문자열 비교를 한다. `h1.compareTo(h2)`
- 위 결과가 0이면(=문자열 사전순으로 같음) NUMBER를 비교한다. `Integer.compare(n1, n2)`
<br>
- …

[개별 - Yebin] 17686

---

programmers/86971/Yebin_86971.java

**[86971번](https://school.programmers.co.kr/learn/courses/30/lessons/86971)**
- 공통 문제로 뽑힌 게 이미 푼거여서 다른 문제를 뽑아서 풀었다.
<br>
<br>
- 트리의 엣지를 하나 끊어서 네트워크를 두개로 분할하는 문제
- 엣지가 최대 99개이므로 완전 탐색이 가능하다
- 트리의 구조가 편향되지 않는다는 보장이 없으니 반복문을 활용한 dfs로 한 네트워크의 노드 개수를 세야 겠다
<br>
<br>
- 완전탐색 
- dfs
<br>
- 인접 리스트로 그래프 표현
- 계산의 편의를 위해 노드 번호를 {1 ~ n} 에서 {0 ~ n-1}로 대치
- List<List<Integer>> graph에 노드 번호와 그에 인접한 노드들을 저장
- 전선이 끊어졌다고 생각하고 그래프의 노드 개수 세기 
- 모든 전선에 대해 그 전선을 제외하고 dfs 탐색을 한다
- Stack에 넣기 전에 방문처리를 해서 메모리를 관리한다 
- 차이의 최솟값 반환
- 그래프가 2개로 나눠진 경우에 대해서만 차이를 계산한다
<br>
- 시간복잡도 : 인접 그래프 만드는데 O(n), dfs 탐색 시 O(n).
- 공간복잡도 : 인접 그래프 O(n^2), dfs 스택 O(n).
<br>
<br>
<br>
<br>
30분
<br/>

[개별 - Yebin] 86971 

---

programmers/92342/Suhwa_92342.java

**[92342번](https://school.programmers.co.kr/learn/courses/30/lessons/92342)**
<br>
<br>
라이언이 어피치를 이기는 화살 조합을 찾는 문제. 이때 최종 화살조합은 주어진 조건(어피치와의 점수차 및 아랫점수 화살이 더 많을때)에 따라 최대이익 화살조합이어야함.
<br>
<br>
처음에 라이언이 어피치를 이기되,최대점수차+같은점수차일경우 아랫점수많은대로
의 화살 조합에서 dp나 그리디를 생각함. 
그러나 라이언이 화살을 쏘는 경우는 0~10점까지 11개 밖에 되지 않음 -> 완탐으로 품
<br>
1. 주어진 어피치의 점수에 의거해 라이언이 점수를 얻을수있는 최소 화살개수를 각 점수대별로 구함 : neededArrow
2. neededArrow에서 각 점수별 화살들을 뽑아 총합이 n 점이 되도록 조합을 구성
3. 각 조합에서 총합이 n 점이 되면 
(1)어피치를 이기는지 
(2)이전 최대조합에 비해 어피치는 더큰 점수로 이기는지
(3) 이전 최대조합에 비해 같은 점수로 이기면 아랫점수 화살이 더 많은지 
검사하여 answer update
<br>
완탐이라 고려크게안함. 아마 뒤지게 비효율적일것...
<br>
<br>
1. 어피치-라이어 점수 계산 오류...
n점 : 어피치=라이언=0 이면 누구도 점수를 얻지 못하는데 이걸 깜빡했다가 라이언이 어피치를 절대 이기지 못하는 경우가 생겨버림 ㅋㅋㅋ
2. answer update... …

[공통 - Suhwa] 92342

---

programmers/42895/Minseon_42895.java

**[프로그래머스 42895번](https://school.programmers.co.kr/learn/courses/30/lessons/42895)**
<br>
<br>
숫자 N과 사칙연산만으로 number를 만들 때 N의 개수의 최솟값을 구하는 문제
<br>
<br>
DP
<br>
- 처음에는 이전의 계산값에 사칙연산과 N을 뒤에 붙이는 BFS 풀이를 생각했었는데, 이렇게 푸니까 괄호를 고려할 수 없게 되었다.
- 예를 들면, N을 4개 써야 할 때 bfs로 풀면 1->2->3->4로 하나씩 N을 늘려가며 풀게 되어 (N+N) + (N+N)과 같이 N을 2개 쓴 값끼리의 연산은 고려하지 않게 된다.
- N을 i개 써서 만든 값을 set에 저장하고, 괄호를 고려하여 N을 사용한 개수를 기준으로 계산한다.
- 즉, N을 4개 썼다면, 1개, 3개끼리 연산 / 2개, 2개끼리 연산 / 3개, 1개끼리 연산
- 계산한 값을 i번째 인덱스의 set에 저장하고, 계산이 끝나면 그 set에 number가 있는지 확인한다.
<br>
O(n^3)이지만 N의 최댓값이 9이므로 사실상 상수시간.
<br>
<br>
처음에 괄호를 생각 못하고 풀었다가 절반만 맞았음
<br>
<br>
소요 시간 : 1시간 20분
<br/>

[개별 - Minseon] 42895

---

programmers/62048/Minseon_62048.java

**[프로그래머스 62048번](https://school.programmers.co.kr/learn/courses/30/lessons/62048)**
<br>
<br>
직사각형을 두 개의 직각삼각형으로 나눴을 때 1*1크기의 정사각형의 개수를 구하는 문제
<br>
<br>
수학
<br>
- 대각선은 y = h/w*x 이다.
- 직각삼각형을 기준으로 쓸 수 있는 정사각형의 개수는 일차함수에 0 ~ w-1를 대입한 값에서 소수점을 버린 값의 합이다.
- 구한 직각삼각형에서 쓸 수 있는 정사각형의 개수 * 2를 해주면 된다.
- 정사각형은 w*h - w, 너비 또는 높이가 1이면 대각선이 모든 정사각형을 통과하므로 0
<br>
O(n)
<br>
<br>
long 캐스팅 다 했다고 생각했는데 자꾸 12, 14번 틀려서 뭐지 했는데 넓이 구할 때 캐스팅을 안해서 그런 거였음;;;
<br>
<br>
소요 시간 : 35분
<br/>

[공통 - Minseon] 62048

---

programmers/1843/Minseon_1843.java

**[프로그래머스 1843번](https://school.programmers.co.kr/learn/courses/30/lessons/1843)**
<br>
<br>
덧셈과 뺄셈으로만 이루어진 식에서 결합법칙을 활용해서 연산 결과를 최대로 만드는 문제.
<br>
<br>
DP
<br>
1. 숫자와 연산자를 분리해서 각각 int, String 배열로 만든다.
2. 처음에는 자기 자신 > 자신과 자신의 오른쪽 숫자 > 3, 4, 5....으로 간격을 늘려가며 최댓값과 최솟값을 구한다.
- 예를 들어, `1 - 3 + 5 - 8`이라는 식이 주어지면,
1. 간격이 0일 때는 자기 자신만 연산할 수 있으므로 자기 자신이 최댓값이자 최솟값. `[1, 3, 5, 8]`
2. 간격이 1일 때 역시 자기 자신과 오른쪽을 연산한 값이 최댓값이자 최솟값이다. `[1-3, 3+5, 5-8]`
3. 간격이 2일 때, `1 - 3 + 5`만 따로 보면 `(1-3) + 5`와 `1 - (3+5)`로 나눌 수 있다. 둘 중 최댓값과 최솟값을 각각 저장하면 된다.
4. 간격이 3일 때 역시 `(1-3+5의 최댓값 또는 최솟값) - 8`과 `1 - (3+5-8의 최댓값 또는 최솟값)`으로 나눌 수 있다.
- 각 단계에서 최댓값과 최솟값을 구하는 방법은 연산자에 따라 갈린다.
- A+B이면 최댓값은 `A의 최댓값 + B의 최댓값`이 되고, 최솟값은 `A의 최솟값 + B의 최솟값`이 된다.
- A-B이면 최댓값은 `A의 최댓값 - B의 최솟값`이 되고, 최솟값은 `A의 …

[개별 - Minseon] 1843

---

programmers/12978/Minseon_12978.java

**[프로그래머스 12978번](https://school.programmers.co.kr/learn/courses/30/lessons/12978)**
<br>
<br>
1번 정점에서 K 시간 이하로 갈 수 있는 정점의 개수를 구하는 문제.
<br>
<br>
BFS인줄 알았으나 플로이드-워셜이었던
<br>
- 인접행렬을 구한다. 이때, 주어진 시간 중 최단 시간을 저장한다.
- 플로이드-워셜 알고리즘을 이용해서 정점 간의 최단시간을 구한다.
- graph[1] 중에서 값이 K 이하인 인덱스를 찾는다.
<br>
O(N^3)이지만 N의 최댓값이 50이라 괜찮다.
<br>
<br>
bfs로 풀었더니 메모리 초과가 나서 플로이드-워셜로 순회.
<br>
<br>
소요 시간 : 32분
<br/>

[공통 - Minseon] 12978

---

programmers/72415/Minseon_72415.java

**[프로그래머스 72415번](https://school.programmers.co.kr/learn/courses/30/lessons/72415)**
<br>
<br>
커서를 이동해서 모든 카드 쌍을 제거할 수 있는 최소 키 조작 횟수를 구하는 문제. 
- 커서를 이동하는 방식은 방향키로 한 칸씩 이동하는 방식과 Ctrl + 방향키로 해당 방향에 가장 가까운 카드로 이동하는 방식이 있다.
- 커서 이동에 조작 횟수 1번씩, 카드를 선택하는(enter 키를 누르는) 데 조작 횟수 1번씩 계산.
<br>
<br>
BFS + Backtracking
<br>
- 카드를 어떤 카드쌍부터 제거하고, 카드쌍 중에서도 어떤 카드를 먼저 제거하냐에 따라 조작 횟수가 달라진다.
- 카드 번호 별로 좌표를 저장한다.
- 백트래킹을 이용해 카드쌍의 순서를 생성한다.
- 해당 카드쌍을 제거했을 때의 최소 조작 횟수를 구한다.
- 최소 조작 횟수는 bfs를 이용해서 한 방향에 대해 방향키로 이동했을 때와 ctrl+방향키로 이동했을 때를 모두 구한다.
<br>
재귀호출의 깊이가 깊지 않으므로 O(n)에 가깝다.
<br>
<br>
처음에 bfs만 써서 풀었는데 메모리 초과 남. 로직 자체는 엄청 어려운 건 아닌데 구현이 복잡하다.
<br>
<br>
소요 시간 : 1시간 43분
<br/>

[공통 - Minseon] 72415

---

programmers/250135/Minseon_250135.java

**[프로그래머스 250135번](https://school.programmers.co.kr/learn/courses/30/lessons/250135)**
<br>
<br>
시작 시간부터 종료 시간까지 시침과 분침이 초침과 겹치는 횟수를 구하는 문제.
- 시침, 분침, 초침이 모두 겹칠 때는 1번으로 친다.
<br>
<br>
구현
<br>
- (0시 0분 0초 \~ 종료 시간까지 겹치는 횟수) - (0시 0분 0초 \~ 시작 시간까지 겹치는 횟수)를 구한다.
- 시침이 초침과 겹치는 횟수 : 12시간(43200초) 동안 719번(11시에서 12시 넘어갈 때 안 겹침)
- 분침이 초침과 겹치는 횟수 : 1시간(3600초) 동안 59번(59분에서 00분 넘어갈 때 안 겹침)
- 시작 시간이 울리는 시간일 때 보정값 넣어주기
<br>
상수 시간 소요
<br>
<br>
처음에 시작 시간부터 시침, 분침을 직접 이동시켰는데 예외 처리가 힘들어서 구현 방식을 바꿨다.
<br>
<br>
소요 시간 : 1시간
<br/>

[공통 - Minseon] 250135

---

programmers/62050/Minseon_62050.java

**[프로그래머스 62050번](https://school.programmers.co.kr/learn/courses/30/lessons/62050)**
<br>
<br>
정사각형 모양의 배열의 각 칸에 높이가 지정되어 있을 때 사다리 설치 비용의 최솟값을 구하는 문제.
- 이동은 상,하,좌,우 한 칸씩 이동
- 두 칸의 높이차가 height 이하면 비용이 들지 않고, height보다 크면 높이차 만큼의 비용을 들여서 사다리를 설치해야 한다.
<br>
<br>
BFS + Heap
<br>
- bfs로 하되, queue를 비용을 오름차순 정렬한 heapq로 바꾸고, queue에는 현재 위치에서 갈 수 있는 칸을 넣는다.
- 높이차가 height보다 낮으면 cost를 0으로 설정. 크면 높이차로 설정. -> 관련 데이터는 Land 클래스를 만들어 비용 정보를 저장한다.
- 이미 방문한 곳은 queue에 넣지 않는다.
- 현재 위치가 방문하지 않은 곳이면 총 비용에 현재 위치의 사다리 설치 비용을 더한다.
<br>
while문에서 O(N), heapq에서 add, poll하는 데 O(logN)이므로 O(NlogN)
<br>
<br>
처음에 순수 bfs로만 풀었다가 메모리 초과가 났다.
<br>
<br>
소요 시간 : 1시간 43분
<br/>

[개별 - Minseon] 62050

---

programmers/12985/Minseon_12985.java

**[프로그래머스 12985번](https://school.programmers.co.kr/learn/courses/30/lessons/12985)**
<br>
<br>
대진표에서 A와 B가 처음 만나는 라운드를 구하는 문제.
<br>
<br>
구현
<br>
A, B가 만나기 전까지는 계속 이길 것이므로 A == B가 될 때까지 이겼을 때의 번호를 부여한다. 이때 /2를 했을 때 0이 되는 것을 방지하기 위해 +1을 해준 다음 /2해준다.
<br>
O(logN)
<br>
<br>
<br>
<br>
소요 시간 : 12분
<br/>

[공통 - Minseon] 12985

---

programmers/49191/Minseon_49191.java

**[프로그래머스 49191번](https://school.programmers.co.kr/learn/courses/30/lessons/49191)**
<br>
<br>
경기 결과가 주어질 때, 순위를 정확하게 알 수 있는 선수의 수를 구하는 문제.
- 경기 결과는 [A, B] 순서로 주어지는데, 이는 A가 B를 이겼음을 의미한다.
<br>
<br>
플로이드-워셜
<br>
- 승리 횟수 + 패배 횟수 == n-1이면 자신을 제외한 모든 선수와의 관계를 알 수 있다는 의미이므로 이는 순위를 확정할 수 있다는 말이 된다.
- 승리 배열과 패배 배열을 만든 다음 각각 플로이드-워셜 알고리즘을 이용해 각 선수와의 최단거리를 구한다.
- 한 선수의 승리 배열의 true값의 합과 패배 배열의 true값의 합이 n-1과 같은지 비교한다.
<br>
O(n^3) 이지만 n의 최댓값이 100이라 괜찮다.
<br>
<br>
<br>
<br>
소요 시간 : 41분
<br/>

[개별 - Minseon] 49191

---

programmers/150368/Suhwa_150368.java

**[150368번](https://school.programmers.co.kr/learn/courses/30/lessons/150368)**
<br>
<br>
각 이모티콘 별로 할인율이 10,20,30,40의 4가지의 경우의 수가있고, 할인된 이모티콘의 set을 유저리스트전체가 하나하나 검사하여 이모티콘플러스가입자와 총매출을 계산해야하는 문제
<br>
<br>
최대유저, 최대 이모티콘의 수가 작은 완탐문제
<br>
완탐이라서 그냥 냅다 하나하나 검사함
<br>
고려안했음...  그러나 최대개수가 적으니까...
<br>
<br>
사실 난 첨보는 문제였음... 이걸 풀라고 준 카카오 미쳤나요?
<br>
<br>
<br/>

[공통 - Suhwa ] 150368

---

programmers/258711/Minseon_258711.java

**[프로그래머스 258711번](https://school.programmers.co.kr/learn/courses/30/lessons/258711)**
<br>
<br>
각 그래프의 한 정점으로 향하는 새로 생성한 정점을 찾고, 도넛 모양 그래프, 막대 모양 그래프, 8자 모양 그래프의 개수를 구하는 문제.
각 그래프는 다음과 같다.
1. 도넛 모양 그래프
2. 막대 모양 그래프
3. 8자 모양 그래프
<br>
<br>
구현
<br>
- 도넛 모양을 제외하면 각 그래프의 특징을 나타내는 정점이 하나씩 있다.
- 8자 모양 그래프: 들어오는 간선이 2개, 나가는 간선이 2개인 정점이 단 하나 존재한다.
- 막대 모양 그래프: 나가는 간선이 없는 정점이 단 하나 존재한다.
- 도넛 모양 그래프는 모든 정점이 들어오는 간선과 나가는 간선의 개수가 모두 1개이다.
- 생성한 정점은 들어오는 간선이 없다.
- 위의 특징을 이용하여 각 그래프의 개수를 구한다.
- 간선 정보를 이용해서 정점의 개수를 구한다.
- 각 정점의 들어오는 간선의 수와 나가는 간선의 수를 배열에 저장한다.
- 1부터 n까지 정점을 탐색하며 해당 조건을 만족하는 정점을 찾으면 answer 배열을 업데이트 한다.
- 전체 그래프의 개수 - 막대 모양 그래프의 개수 - 8자 모양 그래프의 개수로 도넛 모양 그래프의 개수를 구한다.
- 이때, 전체 그래프의 개수는 생성한 정점의 나가는 간선의 개수이다.
<br>
O(n)
<br> …

[공통 - Minseon] 258711

---

programmers/131130/Minseon_131130.java

**[프로그래머스 131130번](https://school.programmers.co.kr/learn/courses/30/lessons/131130)**
<br>
<br>
- 주어진 배열의 각 원소는 다음으로 확인할 상자의 번호(인덱스)가 있는데, 사이클이 만들어질 때까지 확인한 상자의 개수가 해당 그룹의 점수가 된다.
- 여러 그룹의 점수 중 두 개 그룹의 점수를 곱한 값이 최종 점수가 되는데 그 값의 최댓값을 구하는 문제.
- 이때, 하나의 그룹만 나온다면 점수는 0점으로 처리한다.
<br>
<br>
DFS
<br>
- dfs를 이용해 상자 번호를 계속 따라가며 상자의 개수를 센다.
- 가장 큰 값과 그 다음으로 큰 값을 저장하는 변수를 만들어서 그룹의 점수와 비교하여 업데이트 한다.
<br>
상자 안에 든 번호가 중복된 값이 없으므로 O(n)
<br>
<br>
<br>
<br>
소요 시간 : 10분
<br/>

[개별 - Minseon] 131130

---

programmers/43164/Minseon_43164.java

**[프로그래머스 43164번](https://school.programmers.co.kr/learn/courses/30/lessons/43164)**
<br>
<br>
편도 항공권 정보가 주어지면 주어진 모든 항공권을 이용해서 방문하는 공항의 순서를 구하는 문제
- 이때, 경로가 여러 개이면 알파벳 순서가 앞서는 경로로 처리
<br>
<br>
해시, DFS
<br>
- 해시맵과 우선순위 큐를 이용해 항공권 정보를 저장한다.
- key는 공항 이름, value는 해당 공항에서 갈 수 있는 공항을 알파벳 순으로 정렬한 리스트(우선순위 큐를 이용해 알파벳 순으로 정렬)
- 알파벳 순으로 방문했을 때 주어진 항공권을 모두 사용할 수 없는 경우가 있을 수 있으므로 dfs를 이용해서 주어진 항공권을 모두 사용할 수 있는 경로를 찾는다.
- 현재 공항에서 갈 수 있는 공항을 poll하여 자식 경로를 찾아 부모 경로에 병합하는 방식
<br>
O(NlogN)
<br>
<br>
<br>
<br>
소요 시간 : 56분
<br/>

[개별 - Minseon] 43164

---

programmers/92344/Minseon_92344.java

**[프로그래머스 92344번](https://school.programmers.co.kr/learn/courses/30/lessons/92344)**
<br>
<br>
N*M 배열의 각 칸에 건물의 내구도가 주어져 있고 skill 배열을 통해 적의 공격과 아군의 회복 스킬이 주어질 때, 스킬이 모두 끝났을 때 내구도가 0보다 큰(파괴되지 않은) 건물의 개수를 구하는 문제.
- 스킬 범위는 (r1, c1) ~ (r2, c2) 크기의 직사각형 범위
- 적의 공격 스킬은 degree만큼 내구도를 깎고, 아군의 회복 스킬은 degree만큼 내구도를 복구한다.
- n*m(최대 1백만), skill의 크기(최대 25만)가 굉장히 큼
<br>
<br>
누적합
<br>
cf) 2차원 배열의 누적합
|0|-2|-2|0|
|---|---|---|---|
|0|-2|-2|0|
|0|0|0|0|
을 만들고 싶다면
|0|-2|0|2|
|---|---|---|---|
|0|0|0|0|
|0|2|0|-2|
로 배열을 만들어서 x축 방향으로 누적합을 구하고, y축 방향으로 누적합을 구하면 된다.
- 누적합 알고리즘을 이용해서 스킬을 모두 적용했을 때의 배열을 만든다.
- r1, c1, r2, c2가 주어지면, (r1, c1)은 degree * -1 or 1, (r1, c2+1)은 -degree * -1 or 1, (r2+1, c1)은 -degree * -1 or 1, (r2+1, c2+1)은 degree * -1 or 1을 각각 더한다.
- skill 배열에 있는 …

[공통 - Minseon] 92344
